---
title: "Updates to port profile images"
author: "Max Schofield"
date: "2023-12-14"
output:
  html_document:
    df_print: paged
  df_print: default
  html_notebook: null
highlight: pygments
toc: yes
toc_float:
  toc_collapsed: yes
toc_depth: 2
editor_options:
  chunk_output_type: inline
---

```{=html}
<style>
body {
text-align: left}
</style>
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=F, warning=F, include=FALSE}
load_or_install_libraries <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
load_or_install_libraries( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rgeos", "ggspatial") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)

# if (!require("extrafont"))
#   install.packages("extrafont")

# # Unfortunately `extrafont::font_import()` will fail on latest Rttf2pt1 package...
# # so we need to install old version
# devtools::install_version("Rttf2pt1", version = "1.3.8")
# 
# # Import fonts to R
# # This will take few minutes
# extrafont::font_import()

# remove a package causing issues 
#detach("package:plyr", unload=TRUE)
```

```{r connection to BQ, echo=F, warning=F, include=FALSE}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```


```{r connection to BQ, echo=F, warning=F, include=FALSE}
senegal_gaps <- read.csv(here::here("data",".", "senegal_port_profile_ais_gaps_unfiltered_04Jul2023.csv"), header=T)

senegal_gaps$gap_start_r <- as.POSIXct(senegal_gaps$gap_start, format='%Y-%m-%d %H:%M:%S', tz='UTC')

time_period <- filter(senegal_gaps, between(gap_start_r,
      as.POSIXct("2021-10-01 00:00:00 UTC",format='%Y-%m-%d %H:%M:%S', tz='UTC'),
      as.POSIXct("2021-11-01 00:00:00 UTC",format='%Y-%m-%d %H:%M:%S', tz='UTC')))

# set plot limits bound on the data
bounding_wa <- transform_box(xlim = c(-20, -14),
                          ylim = c(16, 8),
                          output_crs = 4326)

# gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
trawl_gaps <- time_period %>% 
  filter(main_class == 'trawlers', gap_hours > 12, main_flag != 'SEN')  

on <- dplyr::select(trawl_gaps, gap_id, lat=on_lat, lon=on_lon, gap_hours)
on$gp_event <- 'on'

off <- dplyr::select(trawl_gaps, gap_id, lat=off_lat, lon=off_lon, gap_hours)
off$gp_event <- 'off'

trawl_gaps_re <- bind_rows(on, off)

# map of ON AND OFF MAP
trawl_gaps_re %>% 
  mutate(gap_hours_alt = if_else(gp_event == "off", gap_hours, as.numeric(NA))) %>%
ggplot() + 
    geom_gfw_outline(theme = "dark") +
    geom_gfw_eez(theme = 'dark', alpha = 0.9) +
    geom_gfw_land(theme = 'dark') +
  # geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
  geom_path(aes(x = lon, y = lat, colour = gap_hours, group = gap_id), size = 1, alpha = 0.4) +
  geom_point(aes(x = lon, y = lat, colour = gap_hours, fill = gap_hours), size = 2, shape = 21, alpha = 0.6) +
  labs(title = "AIS gap events in for all trawlers",
       subtitle = "October 2021",
       x = "Longitude", 
       y= "Latitude") +
  scale_colour_viridis_c(name = "AIS gap (hours)",
                         begin = 0.2,
                         end = 1.0,
                         option = "viridis",
                         limits = c(12, 48),
                         oob = scales::squish,
                         breaks = c(12, 14, 18, 24, 48),
                         labels = c("12", "14", "18", "24", "48")) +
  scale_fill_viridis_c(name = "AIS gap (hours)",
                         begin = 0.2,
                         end = 1.0,
                         option = "viridis",
                         limits = c(4, 48),
                         oob = scales::squish,
                         breaks = c(12, 14, 18, 24, 48),
                         labels = c("12", "14", "18", "24", "48"),
                       na.value = NA) +
  scale_alpha_manual(values = c(0, 1)) +
  # scale_x_continuous(breaks = c(-25, -15, -5, 5)) +
  guides(fill = "none", alpha = "none")  +
 theme(panel.background = element_rect(fill = "#C9D2D3"),
        panel.grid.major = element_line(color = "#B2BEB5",),
      plot.title = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#363c4c',
                                size = 18),
      plot.subtitle = element_text(family = 'Roboto',
                                   color = '#363c4c',
                                   size = 16),

      strip.text = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#363c4c',
                                size = 18),
        
      legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 14),
      legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 18),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(3, 'mm'),
      legend.key.width = unit(20,'mm'),
      axis.title = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#848b9b',
                                size = 18),
      axis.text = element_text(family = 'Roboto',
                               color = '#848b9b',
                               size = 14),
      strip.background = element_rect(color="#d6c7db", fill="#d6c7db", linetype="solid"),
     plot.margin=grid::unit(c(0,0,0,0), "null")) +
  coord_sf(xlim = c(bounding_wa$box_out[['xmin']], bounding_wa$box_out[['xmax']]),
           ylim = c(bounding_wa$box_out[['ymin']], bounding_wa$box_out[['ymax']]),
           crs = bounding_wa$out_crs)

ggsave(filename = here::here('figures', "on_off_gaps_map.png"),width = 40, height = 25, units = "cm")

```
