---
title: "AIS coverage around ports"
author: "Max Schofield"
date: "2023-12-18"
output:
  html_document:
    df_print: paged
  df_print: default
  html_notebook: null
highlight: pygments
toc: yes
toc_float:
  toc_collapsed: yes
toc_depth: 2
editor_options:
  chunk_output_type: inline
---

```{=html}
<style>
body {
text-align: left}
</style>
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=F, warning=F, include=FALSE}
load_or_install_libraries <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
load_or_install_libraries( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rgeos", "ggspatial") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)

# if (!require("extrafont"))
#   install.packages("extrafont")

# # Unfortunately `extrafont::font_import()` will fail on latest Rttf2pt1 package...
# # so we need to install old version
# devtools::install_version("Rttf2pt1", version = "1.3.8")
# 
# # Import fonts to R
# # This will take few minutes
# extrafont::font_import()

# remove a package causing issues 
#detach("package:plyr", unload=TRUE)
```

```{r connection to BQ, echo=F, warning=F, include=FALSE}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```

```{r set parameters for coverage maps, echo=FALSE, warning=FALSE, include=FALSE}

# set upper limit
up_lim <- 1000 
#set plot center 
new_center <- -20

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=-20 +wktext"

# set plot limits for Pacific 
bounding_atlantic <- transform_box(xlim = c(-21, -15),
                          ylim = c(10.5, 16.5),
                          output_crs = best_proj)

# plotting reolution for rasters
res <- 0.5
```

# Satelitte Coverage 
## All Data Types

## Class A

```{r download type A proto messages, echo=F, warning=F}
q_coverage_v2 <- readr::read_file(file = here::here("queries", "ais_coverage", "proto_ais_messages_type.sql"))

west_africa_class_a <- fishwatchr::gfw_query(query = glue::glue(q_coverage_v2,
                  start_date = "'2023-01-01'",
                  end_date = "'2023-07-01'", 
                  min_lat = "10", 
                  max_lat = "17", 
                  min_lon = "-21", 
                  max_lon = "-15", 
                  type = "'A'"),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r Class A Satelitte coverage Senegal, echo=F, warning=F}

west_africa_class_a$lat_bin2 <- round(west_africa_class_a$lat_bin / res) * res
west_africa_class_a$lon_bin2 <- round(west_africa_class_a$lon_bin / res) * res

waf <- west_africa_class_a %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(sat_pos = sum(sat_pos),
              sat_pos_ttl  = sum(sat_pos_ttl),
              segments = sum(segments)) %>%
      ungroup() %>%
        mutate(sat_prop = sat_pos / segments,
               sat_prop_alt = sat_pos_ttl/segments)

colnames(waf)[colnames(waf) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')
# sat_perf <- waf %>% mutate(sat_prop = sat_pos / segments,
#                            sat_prop_alt = sat_pos_ttl /segments )
  
atlantic_map <- waf %>%
  recenter_raster(raster_df = .,
                  res = 0.5,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'sat_prop',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = sat_prop)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,1),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Proportion', 
           title = 'Class A Satelitte AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')  
  
  
ggsave(here::here("outputs", "figures", "AIS coverage", "senegal_sat_ais_class_A_cov_v0.5.png"), width = 8, height = 10)

```

```{r Class B Satelitte coverage Senegal, echo=F, warning=F}

west_africa_class_b <- fishwatchr::gfw_query(query = glue::glue(q_coverage_v2,
                  start_date = "'2023-01-01'",
                  end_date = "'2023-07-01'", 
                  min_lat = "10", 
                  max_lat = "17", 
                  min_lon = "-21", 
                  max_lon = "-15",
                  type = "'B'"),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r Class B Satelitte coverage Senegal map, echo=F, warning=F}

# sat_perf <- west_africa_class_b %>% mutate(sat_prop = sat_pos / segments )

west_africa_class_b$lat_bin2 <- round(west_africa_class_b$lat_bin / res) * res
west_africa_class_b$lon_bin2 <- round(west_africa_class_b$lon_bin / res) * res

waf_b <- west_africa_class_b %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(sat_pos = sum(sat_pos),
              sat_pos_ttl  = sum(sat_pos_ttl),
              segments = sum(segments)) %>%
      ungroup() %>%
        mutate(sat_prop = sat_pos / segments,
               sat_prop_alt = sat_pos_ttl/segments)

colnames(waf_b)[colnames(waf_b) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')
  
atlantic_map <- waf_b %>%
  recenter_raster(raster_df = .,
                  res = 0.5,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'sat_prop',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = sat_prop)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,1),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Proportion', 
           title = 'Class B Satelitte AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')   

ggsave(here::here("outputs", "figures", "AIS coverage", "senegal_sat_ais_class_B_cov_v0.5.png"), width = 8, height = 10)

```

# Terrestrial Coverage

```{r Terrestrial coverage Senegal, echo=F, warning=F}

west_africa_class_a$lat_bin2 <- round(west_africa_class_a$lat_bin / res) * res
west_africa_class_a$lon_bin2 <- round(west_africa_class_a$lon_bin / res) * res

waf_ter <- west_africa_class_a %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(ter_pos = sum(ter_pos),
              ter_pos_ttl  = sum(ter_pos_ttl),
              segments = sum(segments)) %>%
      ungroup() %>%
        mutate(ter_prop = ter_pos / segments,
               ter_prop_alt = ter_pos_ttl/segments)

colnames(waf_ter)[colnames(waf_ter) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')
  
atlantic_map <- waf_ter %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'ter_prop',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = ter_prop)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,1),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Proportion', 
           title = 'Terrestrial AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')  
  
  
ggsave(here::here("outputs", "figures", "AIS coverage", "senegal_terr_ais_cov0.5.png"), width = 8, height = 10)

```

# Measured AIS reception

```{r download measured ais recepion, echo=F, warning=F}
q_measured <- readr::read_file(file = here::here("queries", "ais_coverage", "measured_ais_reception.sql"))

measured_ais <- fishwatchr::gfw_query(query = glue::glue(q_measured,
                  start_date = "'2023-01-01'",
                  end_date = "'2023-07-01'", 
                  min_lat = "10", 
                  max_lat = "17", 
                  min_lon = "-21", 
                  max_lon = "-15"),
                                 run_query = TRUE,
                                 con = con)$data
```


```{r Test measured AIS class A, echo=F, warning=F}

m_class_a <- filter(measured_ais, ais_class == 'A')

m_class_a$lat_bin2 <- round(m_class_a$lat_bin / res) * res
m_class_a$lon_bin2 <- round(m_class_a$lon_bin / res) * res

m_class_a_new_res <- m_class_a %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(sat_pos_per_day  = sum(sat_pos_per_day ),
              hours  = sum(hours)) 

colnames(m_class_a_new_res)[colnames(m_class_a_new_res) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')

quantile(m_class_a_new_res$sat_pos_per_day)

atlantic_map <- m_class_a_new_res %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'sat_pos_per_day',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = sat_pos_per_day)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,15000),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Daily Positions', 
           title = 'Class A Satelitte AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')  
  
  
ggsave(here::here("outputs", "figures", "AIS coverage", "Class_A_measured_cov_0.5.png"), width = 8, height = 10)

```

```{r Test measured AIS class B, echo=F, warning=F}

m_class_b <- filter(measured_ais, ais_class == 'B')

m_class_b$lat_bin2 <- round(m_class_b$lat_bin / res) * res
m_class_b$lon_bin2 <- round(m_class_b$lon_bin / res) * res

m_class_b_new_res <- m_class_b %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(sat_pos_per_day  = sum(sat_pos_per_day ),
              hours  = sum(hours)) 

colnames(m_class_b_new_res)[colnames(m_class_b_new_res) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')

quantile(m_class_b_new_res$sat_pos_per_day)

atlantic_map <- m_class_b_new_res %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'sat_pos_per_day',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = sat_pos_per_day)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,3500),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Daily Positions',
           title = 'Class B Satelitte AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')  
  
  
ggsave(here::here("outputs", "figures","AIS coverage", "Class_B_measure_cov_0.5.png"), width = 8, height = 10)

```

```{r Test measured AIS Terrestrial, echo=F, warning=F}

m_class_ter <- filter(measured_ais, ais_class == 'A')

m_class_ter$lat_bin2 <- round(m_class_ter$lat_bin / res) * res
m_class_ter$lon_bin2 <- round(m_class_ter$lon_bin / res) * res

m_class_ter_new_res <- m_class_ter %>%
  group_by(lat_bin2, lon_bin2) %>%
    summarise(ter_pos_per_day  = sum(ter_pos_per_day ),
              hours  = sum(hours)) 

colnames(m_class_ter_new_res)[colnames(m_class_ter_new_res) %in% c('lat_bin2','lon_bin2')] <- c('lat_bin','lon_bin')

quantile(m_class_ter_new_res$ter_pos_per_day)

atlantic_map <- m_class_ter_new_res %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'ter_pos_per_day',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = ter_pos_per_day)) +
    geom_gfw_eez(theme = 'light', alpha = 0.8, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,1200),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atlantic$box_out[['xmin']], bounding_atlantic$box_out[['xmax']]),
           ylim = c(bounding_atlantic$box_out[['ymin']], bounding_atlantic$box_out[['ymax']]),
           crs = bounding_atlantic$out_crs) +
      labs(fill = 'Daily Positions',
           title = 'Terrestrial AIS coverage') +
      theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atlantic_map,
                             main_box = bounding_atlantic,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')  
  
  
ggsave(here::here("outputs", "figures", "AIS coverage", "terrestrial_measure_cov_0.5.png"), width = 8, height = 10)

```

<!-- different AIS gap visualizations -->

# AIS Gap images

```{r AIS coverage tables, echo=F, warning=F}
gap_locations <- readr::read_file(file = here::here("queries", "ais_coverage", "ais_gap_locations.sql"))

wa_gap_locations <- fishwatchr::gfw_query(query = glue::glue(gap_locations,
                  start_date = "'2023-01-01'",
                  end_date = "'2023-07-01'", 
                  min_lat = "10", 
                  max_lat = "17", 
                  min_lon = "-21", 
                  max_lon = "-15"),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r connection to BQ, echo=F, warning=F, include=FALSE}

table(wa_gap_locations$geartype)

time_period <- filter(wa_gap_locations, between(gap_start_timestamp,
      as.POSIXct("2023-03-01 00:00:00 UTC",format='%Y-%m-%d %H:%M:%S', tz='UTC'),
      as.POSIXct("2023-04-01 00:00:00 UTC",format='%Y-%m-%d %H:%M:%S', tz='UTC')))

# set plot limits bound on the data
bounding_wa <- transform_box(xlim = c(-20, -14),
                          ylim = c(16, 8),
                          output_crs = 4326)

table(time_period$geartype)

# gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
trawl_gaps <- time_period %>% 
  filter(geartype %in% c('trawlers'), 
         gap_hours > 12, 
         flag != 'SEN'
         )  

on <- dplyr::select(trawl_gaps, gap_id, lat=gap_end_lat, lon=gap_end_lon, gap_hours)
on$gp_event <- 'on'

off <- dplyr::select(trawl_gaps, gap_id, lat=gap_start_lat, lon=gap_start_lon, gap_hours)
off$gp_event <- 'off'

trawl_gaps_re <- bind_rows(on, off)

# map of ON AND OFF MAP
trawl_gaps_re %>% 
  mutate(gap_hours_alt = if_else(gp_event == "off", gap_hours, as.numeric(NA))) %>%
ggplot() + 
    geom_gfw_outline(theme = "dark") +
    geom_gfw_eez(theme = 'dark', alpha = 0.9) +
    geom_gfw_land(theme = 'dark') +
  # geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
  geom_path(aes(x = lon, y = lat, colour = gap_hours, group = gap_id), size = 1, alpha = 0.4) +
  geom_point(aes(x = lon, y = lat, colour = gap_hours, fill = gap_hours), size = 2, shape = 21, alpha = 0.6) +
  labs(title = "AIS gap events for all trawlers",
       subtitle = "March 2023",
       x = "Longitude", 
       y= "Latitude") +
  scale_colour_viridis_c(name = "AIS gap (hours)",
                         begin = 0.2,
                         end = 1.0,
                         option = "viridis",
                         limits = c(12, 48),
                         oob = scales::squish,
                         breaks = c(12, 14, 18, 24, 48),
                         labels = c("12", "14", "18", "24", "48")) +
  scale_fill_viridis_c(name = "AIS gap (hours)",
                         begin = 0.2,
                         end = 1.0,
                         option = "viridis",
                         limits = c(4, 48),
                         oob = scales::squish,
                         breaks = c(12, 14, 18, 24, 48),
                         labels = c("12", "14", "18", "24", "48"),
                       na.value = NA) +
  scale_alpha_manual(values = c(0, 1)) +
  # scale_x_continuous(breaks = c(-25, -15, -5, 5)) +
  guides(fill = "none", alpha = "none")  +
 theme(panel.background = element_rect(fill = "#C9D2D3"),
        panel.grid.major = element_line(color = "#B2BEB5",),
      plot.title = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#363c4c',
                                size = 18),
      plot.subtitle = element_text(family = 'Roboto',
                                   color = '#363c4c',
                                   size = 16),

      strip.text = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#363c4c',
                                size = 18),
      legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 14),
      legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 18),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(3, 'mm'),
      legend.key.width = unit(20,'mm'),
      axis.title = element_text(family = 'Roboto',
                                face = 'bold',
                                color = '#848b9b',
                                size = 18),
      axis.text = element_text(family = 'Roboto',
                               color = '#848b9b',
                               size = 14),
      strip.background = element_rect(color="#d6c7db", fill="#d6c7db", linetype="solid"),
     plot.margin=grid::unit(c(0,0,0,0), "null")) +
  coord_sf(xlim = c(bounding_wa$box_out[['xmin']], bounding_wa$box_out[['xmax']]),
           ylim = c(bounding_wa$box_out[['ymin']], bounding_wa$box_out[['ymax']]),
           crs = bounding_wa$out_crs)

ggsave(filename = here::here("outputs", "figures", "AIS coverage", "ais gaps", "on_off_gaps_map.png"),width = 24, height = 15, units = "cm")

```

# Vessel level AIS coverage  

```{r look at vessel daily ais coverage, echo=F, warning=F}
# vessel_ais_q <- readr::read_file(file = here::here("queries", ".", "vessel_ais_coverage.sql"))
vessel_ais_q <- readr::read_file(file = here::here("queries", "ais_coverage", "vessel_ais_coverage_all.sql"))

daily_voi_ais <- fishwatchr::gfw_query(query = vessel_ais_q,
                                 run_query = TRUE,
                                 con = con)$data

```

```{r vessel level AIS coverage metrics, echo=F, warning=F}

daily_voi_ais$frac_hours <- daily_voi_ais$n_ais_hours / daily_voi_ais$n_voyage_hours 
daily_voi_ais$year <- year(daily_voi_ais$trip_start)

n_distinct(daily_voi_ais$vessel_id)
head(daily_voi_ais)

# look at coverage by vessel
vessel_level <- daily_voi_ais %>% 
  group_by(ssvid, vessel_id, geartype) %>% 
    summarise(
      days = n_distinct(date),
      average_daily_frac_ais = mean(frac_hours),
      ttl_hours = sum(n_ais_hours),
      ttl_voyage_hours = sum(n_voyage_hours),
      ttl_frac_ais = ttl_hours / ttl_voyage_hours
    ) %>% 
    arrange(ttl_frac_ais)

# look at coverage by geartype
gear_average <- vessel_level %>% 
    ungroup() %>% 
      group_by(geartype) %>% 
        summarise(vessels = n_distinct(vessel_id), 
                  average_cov = mean(ttl_frac_ais))
  
```

# Trawlers

## question: Do we want all the vessels activity or just on trips that go to Senegal? 


```{r top 5 trawl vessels, echo=F, warning=F}
# look at coverage graphs for worst performing vessels 
top5_trawlers <- filter(vessel_level, days > 50, geartype == 'trawlers')$ssvid[1:5] 

# single vessel plot
# daily_voi_ais %>%
#   filter(ssvid == top5_trawlers[1]) %>%
#     mutate(frac_hours = n_ais_hours/n_voyage_hours) %>%
#       ggplot() +
#       geom_line(aes(date, frac_hours)) +
#       geom_point(aes(date, frac_hours)) +
#       geom_smooth(aes(date, frac_hours)) +
#       lims(x=c(as.Date('2019-01-01'),as.Date('2021-12-31'))) +
#       labs(y='Proportion of time on AIS', x = 'Date', title = paste('MMSI ', top5_trawlers[1]))
# 

daily_voi_ais %>%
  filter(ssvid %in% top5_trawlers) %>%
    mutate(frac_hours = n_ais_hours/n_voyage_hours) %>%
      ggplot() +
      geom_line(aes(date, frac_hours)) +
      geom_point(aes(date, frac_hours)) +
      geom_smooth(aes(date, frac_hours)) +
      lims(x=c(as.Date('2019-01-01'),as.Date('2021-12-31')), y=c(0,1)) +
      labs(y='Proportion of time on AIS', x = 'Date', title = 'worst performing trawlers') +
      facet_wrap(vars(ssvid))

ggsave(filename = here::here("outputs", "figures", "AIS coverage", 'Vessel_coverage',"trawl_b5_vessels_coverage_2019_2021.png"),
        width = 30, height = 20, units = "cm")
```

```{r look at coverage for bottom 30 trawl vessels by gear, echo=F, warning=F}

plot_dat <- daily_voi_ais %>% 
  filter(geartype == 'trawlers', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(-30, frac_hours) %>% 
                gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
                  dplyr::mutate(freq_lab = ifelse(source %in% c("ttl_ais_hours"), NA, frac_hours)) 


ggplot(data = plot_dat, aes(x=reorder(ssvid, frac_hours, mean, decreasing=TRUE), 
                            y=hours, fill=source)) + 
  geom_bar(stat='identity',position='identity', alpha=0.75) +
  scale_fill_manual(values=gfw_palette('primary')[1:2], labels=c('AIS hours', 'Voyage Hours'))+
  geom_text(aes(label=round(freq_lab,1)),size = 2, position_stack="stack",nudge_y = 100) +
  coord_flip() +
  labs(y='Hours',
       x='MMSI',
       fill='', 
       title='AIS usage of Trawl Vessels', 
       subtitle = '30 vessels with lowest AIS usage fraction') +
  theme_classic() +
  theme(legend.position = 'bottom')
      
ggsave(filename = here::here("outputs", "figures", "AIS coverage", 'Vessel_coverage',"trawl_30_prop_gaps_hours.png"),width = 20, height = 15, units = "cm")
```

```{r Table of AIS usage fractions top n bottom n trawlers, echo=F, warning=F}
n <- 3

top_n_bot_n <- bind_rows(daily_voi_ais %>% 
  filter(geartype == 'trawlers', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                ttl_voyage_days = sum(n_voyage_hours)/24, 
                ttl_ais_days = sum(n_ais_hours)/24,
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(n, frac_hours), 
  daily_voi_ais %>% 
  filter(geartype == 'trawlers', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                ttl_voyage_days = sum(n_voyage_hours)/24, 
                ttl_ais_days = sum(n_ais_hours)/24,
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(-n, frac_hours))

```

# Tuna Purse Seine

```{r look at metrics tuna ps, echo=F, warning=F}
# look at coverage graphs for worst performing vessels 
top5_ps <- filter(vessel_level, days > 300, geartype == 'tuna_purse_seines')$ssvid[1:5] 

daily_voi_ais %>%
  filter(ssvid %in% top5_ps) %>%
    mutate(frac_hours = n_ais_hours/n_voyage_hours) %>%
      ggplot() +
      # geom_line(aes(date, frac_hours)) +
      # geom_point(aes(date, frac_hours)) +
      geom_smooth(aes(date, frac_hours)) +
      lims(x=c(as.Date('2019-01-01'),as.Date('2021-12-31')), y=c(0,1)) +
      labs(y='Proportion of time on AIS', x = 'Date', title = 'worst performing tuna purse seiners') +
      facet_wrap(vars(ssvid))

ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage',"tps_b5_vessels_coverage_2019_2021.png"),
        width = 30, height = 20, units = "cm")
```

```{r look at coverage for bottom tps 30 vessels by gear, echo=F, warning=F}

plot_dat <- daily_voi_ais %>% 
  filter(geartype == 'tuna_purse_seines', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(-30, frac_hours) %>% 
                gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
                  dplyr::mutate(freq_lab = ifelse(source %in% c("ttl_ais_hours"), NA, frac_hours)) 


ggplot(data = plot_dat, aes(x=reorder(ssvid, frac_hours, mean, decreasing=TRUE), 
                            y=hours, fill=source)) + 
  geom_bar(stat='identity',position='identity', alpha=0.5) +
  scale_fill_manual(values=gfw_palette('primary')[1:2], labels=c('AIS hours', 'Voyage Hours'))+
  geom_text(aes(label=round(freq_lab,1)),size = 2, position_stack="stack",nudge_y = 100) +
  coord_flip() +
  labs(y='Hours',
       x='MMSI',
       fill='', 
       title='AIS usage of Tuna Purse Seine Vessels', 
       subtitle = '30 vessels with lowest AIS usage fraction') +
  theme_classic() +
  theme(legend.position = 'bottom')
      
ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage', "tps_proportion_gaps_hours.png"),width = 20, height = 15, units = "cm")
```

# Drifting Longlines 

```{r look at metrics tuna, echo=F, warning=F}
# look at coverage graphs for worst performing vessels 
top5_longliners <- filter(vessel_level, days > 300, geartype == 'drifting_longlines')$ssvid[1:5] 

daily_voi_ais %>%
  filter(ssvid %in% top5_longliners) %>%
    mutate(frac_hours = n_ais_hours/n_voyage_hours) %>%
      ggplot() +
      # geom_line(aes(date, frac_hours)) +
      # geom_point(aes(date, frac_hours)) +
      geom_smooth(aes(date, frac_hours)) +
      lims(x=c(as.Date('2019-01-01'),as.Date('2021-12-31')), y=c(0,1)) +
      labs(y='Proportion of time on AIS', x = 'Date', title = 'worst performing longliners') +
      facet_wrap(vars(ssvid))

ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage',"ll_b5_vessels_coverage_2019_2021.png"), width = 30, height = 20, units = "cm")
```

```{r look at coverage for bottom ll 30 vessels by gear, echo=F, warning=F}

plot_dat <- daily_voi_ais %>% 
  filter(geartype == 'drifting_longlines', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(-30, frac_hours) %>% 
                gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
                  dplyr::mutate(freq_lab = ifelse(source %in% c("ttl_ais_hours"), NA, frac_hours)) 


ggplot(data = plot_dat, aes(x=reorder(ssvid, frac_hours, mean, decreasing=TRUE), 
                            y=hours, fill=source)) + 
  geom_bar(stat='identity',position='identity', alpha=0.5) +
  scale_fill_manual(values=gfw_palette('primary')[1:2], labels=c('AIS hours', 'Voyage Hours'))+
  geom_text(aes(label=round(freq_lab,1)),size = 2, position_stack="stack",nudge_y = 100) +
  coord_flip() +
  labs(y='Hours',
       x='MMSI',
       fill='', 
       title='AIS usage of drifting longline Vessels', 
       subtitle = '30 vessels with lowest AIS usage fraction') +
  theme_classic() +
  theme(legend.position = 'bottom')
      
ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage',"ll_proportion_gaps_hours.png"),width = 20, height = 15, units = "cm")
```

# Carriers

```{r look at metrics carrier, echo=F, warning=F}
# look at coverage graphs for worst performing vessels 
top5_carrier <- filter(vessel_level, days > 300, geartype == 'carrier')$ssvid[1:5] 

daily_voi_ais %>%
  filter(ssvid %in% top5_carrier) %>%
    mutate(frac_hours = n_ais_hours/n_voyage_hours) %>%
      ggplot() +
      # geom_line(aes(date, frac_hours)) +
      # geom_point(aes(date, frac_hours)) +
      geom_smooth(aes(date, frac_hours)) +
      lims(x=c(as.Date('2019-01-01'),as.Date('2021-12-31')), y=c(0,1)) +
      labs(y='Proportion of time on AIS', x = 'Date', title = 'worst performing longliners') +
      facet_wrap(vars(ssvid))

ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage',"carrier_b5_vessels_coverage_2019_2021.png"),
        width = 30, height = 20, units = "cm")
```

```{r look at coverage for bottom carrier 30 vessels by gear, echo=F, warning=F}

plot_dat <- daily_voi_ais %>% 
  filter(geartype == 'carrier', trip_start > as.Date('2019-01-01'))  %>% 
    group_by(ssvid) %>% 
      summarise(ttl_voyage_hours = sum(n_voyage_hours), 
                ttl_ais_hours = sum(n_ais_hours),
                days = n_distinct(date)) %>%
        mutate(frac_hours = ttl_ais_hours/ttl_voyage_hours) %>%
          filter(days > 30) %>%
            ungroup() %>%
              top_n(-30, frac_hours) %>% 
                gather(key = "source", value = "hours", ttl_ais_hours, ttl_voyage_hours) %>%
                  dplyr::mutate(freq_lab = ifelse(source %in% c("ttl_ais_hours"), NA, frac_hours)) 


ggplot(data = plot_dat, aes(x=reorder(ssvid, frac_hours, mean, decreasing=TRUE), 
                            y=hours, fill=source)) + 
  geom_bar(stat='identity',position='identity', alpha=0.5) +
  scale_fill_manual(values=gfw_palette('primary')[1:2], labels=c('AIS hours', 'Voyage Hours'))+
  geom_text(aes(label=round(freq_lab,1)),size = 2, position_stack="stack",nudge_y = 100) +
  coord_flip() +
  labs(y='Hours',
       x='MMSI',
       fill='', 
       title='AIS usage of fish carrier Vessels', 
       subtitle = '30 vessels with lowest AIS usage fraction') +
  theme_classic() +
  theme(legend.position = 'bottom')
      
ggsave(filename = here::here('outputs','figures', 'AIS coverage', 'Vessel_coverage',"carrier_proportion_gaps_hours.png"),width = 20, height = 15, units = "cm")
```



