---
title: "Philippines_port_data"
author: "Max Schofield"
date: "2025-01-31"
output: html_document
---

```{=html}
<style>
body {
text-align: left}
</style>
```

# Setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=F, warning=F, include=FALSE}
load_or_install_libraries <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
load_or_install_libraries( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rgeos", "ggspatial") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)

```

```{r connection to BQ, echo=F, warning=F, include=FALSE}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```

# Non-designated PHL port visit data 
## Set up BQ function parameters

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2023-01-01 00:00:00 UTC'" 
end_date <- "'2025-01-01 00:00:00 UTC'"
start_year <- 2023
end_year <- 2024

port_labels <- '"SUBIC", "SUBIC BAY VICINITY", "SEATRIAL", "PH SUBIC", 
                "W IN SUBIC BAY ONLY", "NAVOTAS", "MANILA", "NIUGAN", 
                "GENERAL SANTOS", "DAVAO", "TORIL"'
port_iso <- '"PHL"'
```

# identify initial voyages

```{r phl non-des voyages 2023-24, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as thr old analysis was so keeping all data consistent. 
voyages_q <- readr::read_file(here::here("queries","PHL", "non-des port voyages.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                          start_date = start_date,
                                          end_date = end_date,
                                          start_year = start_year,
                                          end_year = end_year,
                                          port_labels = port_labels,
                                          port_iso = port_iso),
                                 run_query = TRUE,
                                 con = con)

```


```{r phl non-des voyage events, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

temp_table_voyages <- '`world-fishing-827.scratch_max.phl_nondes_voyages_temp`'

events_q <- readr::read_file(here::here("queries","PHL", "non-des port events.sql"))

fishwatchr::gfw_query(query = glue::glue(events_q, 
                                          temp_table = temp_table_voyages),
                                 run_query = TRUE,
                                 con = con)

```


```{r phl non-des voyage ais cov, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

cov_q <- readr::read_file(here::here("queries","PHL", "non-des ais cov.sql"))

fishwatchr::gfw_query(query = glue::glue(cov_q, 
                                        temp_table = temp_table_voyages,
                                        start_date = start_date,
                                        end_date = end_date),
                                 run_query = TRUE,
                                 con = con)

```

```{r phl non-des voyage combined voyage events & cov, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

temp_table_events <- '`world-fishing-827.scratch_max.phl_nondes_events_temp`'
temp_table_cov <-'`world-fishing-827.scratch_max.phl_nondes_ais_cov_temp`'

combined_q <- readr::read_file(here::here("queries","PHL", "non-des combined.sql"))

non_des_all_data <- fishwatchr::gfw_query(query = glue::glue(combined_q, 
                                         temp_table_voyages = temp_table_voyages,
                                         temp_table_events = temp_table_events,
                                         temp_table_cov = temp_table_cov),
                                 run_query = TRUE,
                                 con = con)$data

write.csv(non_des_all_data, here::here("data", "PHL", paste('PHL_nondes_full_data_', Sys.Date(),".csv", sep='')), row.names=F)
```

# Missing voyages Gen San & Davao 
## Set up BQ function parameters

```{r set date and port parameters mis ves, echo=F, warning=F, include=FALSE}
start_date <- "'2021-01-01 00:00:00 UTC'" 
end_date <- "'2024-01-01 00:00:00 UTC'"
start_year <- 2021
end_year <- 2023

port_labels <- '"GENERAL SANTOS", "DAVAO", "TORIL"'
port_iso <- '"PHL"'
missing_ssvids <- '"416002494", "416501000", "416532000", "440222000", "510076000", "416002900", "416111500",
                   "416367000", "416804000", "510100000", "544117120", "352241000"'


```

# identify initial voyages missed in standard Q

```{r phl gensan dav mis voyages 2023-24, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as thr old analysis was so keeping all data consistent.

voyages_q <- readr::read_file(here::here("queries","PHL", "mis_ves_voyages_gen_dav.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q,
                                          start_date = start_date,
                                          end_date = end_date,
                                          start_year = start_year,
                                          end_year = end_year,
                                          port_labels = port_labels,
                                          port_iso = port_iso, 
                                          missing_ssvids = missing_ssvids),
                                 run_query = TRUE,
                                 con = con)

```


```{r phl gensan dav mis voyages events, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

temp_table_voyages <- '`world-fishing-827.scratch_max.phl_misves_gendav_voyages_temp`'

events_q <- readr::read_file(here::here("queries","PHL", "mis_ves_voyage_events_gen_dav.sql"))

fishwatchr::gfw_query(query = glue::glue(events_q,
                                          temp_table = temp_table_voyages),
                                 run_query = TRUE,
con = con)

```


```{r phl gensan dav mis voyages ais cov, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

cov_q <- readr::read_file(here::here("queries","PHL", "mis_ves_ais_cov_gen_dav.sql"))

fishwatchr::gfw_query(query = glue::glue(cov_q,
                                        temp_table = temp_table_voyages,
                                        start_date = start_date,
                                        end_date = end_date),
                                 run_query = TRUE,
                                 con = con)

```

```{r phl gensan dav mis voyages combined voyage events & cov, echo=F, warning=F, include=FALSE}
# note this in pipe 2.5 as the old analysis was so keeping all data consistent. 

temp_table_events <- '`world-fishing-827.scratch_max.phl_misves_gendav_events_temp`'
temp_table_cov <-'`world-fishing-827.scratch_max.phl_misves_gendav_cov_temp`'

combined_q <- readr::read_file(here::here("queries","PHL", "mis_ves_gen_dav_combined.sql"))

mis_ves_gen_dav_data <- fishwatchr::gfw_query(query = glue::glue(combined_q,
                                         temp_table_voyages = temp_table_voyages,
                                         temp_table_events = temp_table_events,
                                         temp_table_cov = temp_table_cov),
                                 run_query = TRUE,
                                 con = con)$data

write.csv(mis_ves_gen_dav_data, here::here("data", "PHL", paste('PHL_misves_gen_dav_full_data_', Sys.Date(),".csv", sep='')), row.names=F)
```


