---
title: "Port_Program_2025_quarterly"
author: "Max Schofield"
date: "2025-04-07"
output: html_document
---

```{=html}
<style>
body {
text-align: left}
</style>
```

# Setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=F, warning=F, include=FALSE}
load_or_install_libraries <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
load_or_install_libraries( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rgeos", "ggspatial", "ggrepel", "tibble") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)
```

```{r connection to BQ, echo=F, warning=F, include=FALSE}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```

# Cote Divore  

# set parameters for analysis 

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2025-01-01 00:00:00 UTC'" 
end_date <- "'2025-03-31 23:59:59 UTC'"
year <- 2025

country_iso3 <- "'CIV'"
port_name <- "'ABIDJAN'"

# file names
month <- 'Q1'
country <- 'CIV'

# potential MMSIs to force in 
missing_ssvids <- '"231257000", "311001586", "311001574", "311043800", "311040500", "306097000", "311001555", "311001159", "228385700", "306097000", "352004341", "412483273", 
"412483274", "412483275"'

# create a temp table for query 
temp_table_voyages <- '`world-fishing-827.scratch_max.civ_q1_25_all_voyages_temp`'
```

```{r voyages all, echo=F, warning=F, include=FALSE}

voyages_q <- readr::read_file(here::here("queries","proactive", "recent_country_activity_c2_v4.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    missing_ssvids = missing_ssvids,
                                                    temp_table = temp_table_voyages,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)

```

```{r voyages ais coverage, echo=F, warning=F, include=FALSE}

ais_cov_q <- readr::read_file(here::here("queries","proactive", "voyage_ais_coverage_no_port.sql"))

voyages_with_coverage <- fishwatchr::gfw_query(query = glue::glue(ais_cov_q, 
                                                    temp_table = temp_table_voyages,
                                                    start_date = start_date,
                                                    end_date = end_date
                                                    # port_lat_min = port_lat_min,
                                                    # port_lat_max = port_lat_max,
                                                    # port_lon_min = port_lon_min,
                                                    # port_lon_max = port_lon_max
                                                    ),
                                 run_query = TRUE,
                                 con = con)$data

```

```{r add gfw hyperlink for voyage, echo=F, warning=F, include=FALSE}

# base componenets for VV string to accompany port profiles 
base_string_p1 <- 'https://globalfishingwatch.org/map/vessel/'
base_string_p2 <- '?&start='
base_string_p3 <- '&end='
start_date_url <- '2025-01-01'
end_date_url <- '2025-3-31'

#format(voyages_with_coverage$trip_start, format='%Y-%m-%d')

# paste string components together using vessel id, trip start and trip end from data 
voyages_url <- bind_cols(voyages_with_coverage, 
                         vv_url = paste('=HYPERLINK("',
                          base_string_p1,
                          voyages_with_coverage$vessel_id, 
                          base_string_p2, 
                          as.Date(format(voyages_with_coverage$trip_start, format='%Y-%m-%d'))-2, 
                          base_string_p3, 
                          as.Date(format(voyages_with_coverage$trip_end, format='%Y-%m-%d'))+2,
                          '")', sep=''))
```

```{r add in port information for CIV using anchorage stops}
anchorages <- fishwatchr::gfw_query(query = c("SELECT s2id, lat, lon, label, sublabel FROM `world-fishing-827.anchorages.named_anchorages_v20240117` WHERE iso3 = 'CIV'"),
                       run_query = TRUE,
                       con = con)$data

write.csv(anchorages, here::here("data","2025_q1", paste('Abidjan_anchorages','_', Sys.Date(),".csv", sep='')), row.names=F)

table(anchorages$sublabel)

# s2ids for port features of interest 
vridi <- filter(anchorages, sublabel == 'ABIDJAN VRIDI')$s2id
lagoon <- filter(anchorages, sublabel == 'ABIDJAN LAGOON')$s2id
cargo <- filter(anchorages, sublabel == 'ABIDJAN TREICHVILLE CARGO')$s2id
fishing <- filter(anchorages, sublabel == 'ABIDJAN TREICHVILLE FISHING')$s2id
offshore <- filter(anchorages, sublabel %in% c('ABIDJAN OFFSHORE', 'PORT BOUET', 'ABIDJAN PORT BOUET OFFSHORE'))$s2id

port_stops <- voyages_url %>%
  rowwise() %>%
  mutate(abj_lagoon = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% lagoon),
         abj_vridi = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% vridi),
         abj_cargo = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% cargo),
         abj_fishing = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% fishing),
         abj_offshore = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% offshore))

```


```{r format the data to TMT format, echo=F, warning=F, include=FALSE}
# change colnames to be sensible for an externally shared document 
voyages_reformat <- dplyr::select(port_stops, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, AIS_Flag= mmsi_flag, imo, vessel_class_cat=vessel_class_initial, vessel_class_confidence = class_confidence_initial, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, abj_lagoon, abj_vridi, abj_cargo, abj_fishing, abj_offshore, fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, percent_ais_voyage=percent_ais_voyage, vv_url)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
voyages_reformat$encounter <- ifelse(is.na(voyages_reformat$num_encounters), FALSE, TRUE)

# overwrite loitering T/F
voyages_reformat$loitering <- ifelse(is.na(voyages_reformat$num_loitering), FALSE, TRUE)

# overwrite fishing T/F
voyages_reformat$fishing <- ifelse(is.na(voyages_reformat$fishing), FALSE, TRUE)

# overwrite fishing_hs T/F
voyages_reformat$fishing_hs <- ifelse(is.na(voyages_reformat$fishing_hs), FALSE, TRUE)

write.csv(voyages_reformat, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),".csv", sep='')), row.names=F)
```

```{r update changes for CIV, echo=F, warning=F, include=FALSE}
# pull in TMT review data from Matt
tmt_civ <- read.csv(here::here("data","2025_q1", "TMT_feedback", "CIV - Q1 2025.csv"), header=T)

# make MMSI char for joining 
tmt_civ$MMSI <- as.character(tmt_civ$MMSI)

# drop rows with action to remove 
tmt_civ_ret <- tmt_civ %>% filter(!str_detect(Action, "REMOVE"))

# standardise gear changes 
gear_changes <- filter(tmt_civ_ret, Gear.type != "")

gear_corrected <- voyages_reformat %>%
  left_join(
    gear_changes %>%
      select(MMSI, new_vt = vessel_type) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(vessel_type = ifelse(!is.na(new_vt), new_vt, vessel_type)) %>%
  select(-new_vt)

# standardise type changes 
type_changes <- filter(tmt_civ_ret, Vessel.type != "")

type_corrected <- gear_corrected %>%
  left_join(
    type_changes %>%
      select(MMSI, new_vc = vessel_class_cat) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(vessel_class = ifelse(!is.na(new_vc), new_vc, vessel_class)) %>%
  select(-new_vc)

# standardise flag changes 
flag_changes <- filter(tmt_civ_ret, Flag != "")

flag_corrected <- type_corrected %>%
  left_join(
    flag_changes %>%
      select(MMSI, new_flag = Flag) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(Flag = ifelse(!is.na(new_flag), new_flag, Flag)) %>%
  select(-new_flag)

# mannually correct vessel name 
flag_corrected$vessel_name[flag_corrected$MMSI == '312797000'] <- 'BAO WIN'


# # examine new vessels added with code change 
new_ves <- filter(voyages_reformat, !MMSI %in% tmt_civ$MMSI)
# # MSC UNITE VI & OBS VENUS - both look like they should drop out of the analysis 

# # manual addition of missing vessel
# extra <- data.frame("ATLANTIC GLORY", "312864000", "Belize", "Belize", "8919403", "Fishing","high",  "Fishing", "tuna_purse_seines", "CIV", "ABIDJAN", as.POSIXct("2025-03-20 08:26:00", format = "%Y-%m-%d %H:%M:%S"), "4", as.POSIXct("2025-03-21 09:00:00", format = "%Y-%m-%d %H:%M:%S"), "4", "1","TEMA", FALSE, FALSE, TRUE, FALSE, FALSE, NA, NA, FALSE, NA, FALSE, 0, FALSE, 0, 100, "")
# colnames(extra) <- colnames(class_corrected)
# 
# additions <- rbind(class_corrected, extra)
# 
# # drop out vessels that aren't relevant 
# final_list <- filter(class_corrected,  MMSI %in% filter(tmt_gha, Relevant=="Use")$MMSI) 

# remove vessels from TMT review saying drop 
plot_df_civ <-  filter(flag_corrected, MMSI %in% unique(tmt_civ_ret$MMSI))


write.csv(plot_df_civ, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),"_v2.csv", sep='')), row.names=F)
```

```{r CIV graphs, echo=F, warning=F, include=FALSE}
install.packages("viridis")
library(viridis)


# flag pie chart 
data <- plot_df_civ %>%
  group_by(Flag) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(Flag, "\n", vessels)
  )

ggplot(data, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = Flag)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  #scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  #scale_fill_viridis(option="plasma", discrete=TRUE)+
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 3,
    nudge_x = 0.3,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Côte D'ivore voyages by Flag")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "civ_fishing_flags_",str_replace_all(Sys.Date(), '-','_'),"v2.png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')

#------------------------------------------------------
# Vessel class pie chart  
plot_dat_class <- plot_df_civ %>%
  group_by(vessel_class) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_class, "\n", vessels)
  ) 

ggplot(plot_dat_class, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_class)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  # geom_text_repel(
  #   aes(x = 3.5, y = (ymin + ymax)/2, label = label),
  #   size = 3,
  #   nudge_x = 0.3,
  #   segment.color = "grey50",   # optional: draws a line from label to pie
  #   show.legend = FALSE,
  #   direction = "y",
  #   force = 1,
  #   max.overlaps = 20
  # ) +
  ggtitle("Côte D'ivore voyages \n by vessel type")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "vessel_class_",str_replace_all(Sys.Date(), '-','_'),"v2.png")), 
       units = 'cm', 
       width = 7, 
       height = 7,
       bg = '#f7f7f7')


#------------------------------------------------------
# Vessel type pie chart  
plot_dat <- plot_df_civ %>%
  group_by(vessel_type) %>%
  summarize(vessels = n()) %>%
    mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_type, "\n", vessels)
  ) 

ggplot(plot_dat, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_type)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  ggtitle("Côte D'ivore voyages by gear")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_gears_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')


```

```{r CIV pull in the fishing data, echo=F, warning=F, include=FALSE}

q_fishing_events <- readr::read_file(here::here("queries","proactive", "proactive_fishing_locations.sql"))

fishing <- fishwatchr::gfw_query(query = glue::glue(q_fishing_events,
                                               voyages_table = "`world-fishing-827.scratch_max.civ_q1_25_all_voyages_temp`" 
                                               ),
                                 run_query = TRUE,
                                 con = con)$data

# sense check the data 
fishing %>%
    group_by(ssvid) %>%
      summarise(positions = n(), 
                min_date = min(event_start), 
                max_date = max(event_end))

# add gear from TMT review 
gear <- distinct(dplyr::select(plot_df_civ, MMSI, Flag, vessel_type)) %>% 
  mutate(ssvid=as.character(MMSI))

fishing_data <- left_join(fishing, gear, by = join_by(ssvid))


```

```{r CIV voyage activity longline maps, echo=F, warning=F, include=FALSE}
# bin the data
fishing_data$lat_bin <- round(fishing_data$lat_mean/0.5)*0.5
fishing_data$lon_bin <- round(fishing_data$lon_mean/0.5)*0.5


# count positions in each lat lon bin
ps_raster <- 
  # filter out low speeds while vessel in port 
  #filter(fishing_data, vessel_type %in% c('purse_seine_support','tuna_purse_seines')) %>%
  filter(fishing_data, vessel_type %in% c('tuna_purse_seines')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# look at data distribution
quantile(ps_raster$fishing_hours)

# set upper limit
up_lim <- 200 
#set plot center 
new_center <- 40

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=40 +wktext"

# set plot limits bound on the data
bounding_atl <- transform_box(xlim = c(-25, 5),
                          ylim = c(10, -8),
                          output_crs = best_proj)

# map for atlantic longline 
atl_full <- ps_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atl$box_out[['xmin']], bounding_atl$box_out[['xmax']]),
      ylim = c(bounding_atl$box_out[['ymin']], bounding_atl$box_out[['ymax']]),
      crs = bounding_atl$out_crs) +
    # scale_x_continuous(breaks = custom_breaks, labels = custom_labels)+
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light') +
    theme(legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 6),
        legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 6),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(2, 'mm'),
      legend.key.width = unit(15,'mm'))


fishwatchr::add_little_globe(atl_full,
                             main_box = bounding_atl,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures','q1_25_proactive', paste0(country,"_", month,"_", "ps_map-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 15, 
       height = 17,
       bg = '#f7f7f7')

```


# Ghana 

# set parameters for analysis 

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2025-01-01 00:00:00 UTC'" 
end_date <- "'2025-03-31 23:59:59 UTC'"
year <- 2025

country_iso3 <- "'GHA'"
port_name <- "'TEMA', 'TAKORADI'"

# file names
month <- 'Q1'
country <- 'GHA'

# create a temp table for query 
temp_table_voyages <- '`world-fishing-827.scratch_max.gha_q1_25_all_voyages_temp`'

# potential MMSIs to force in 
missing_ssvids <- '"577030000", "311001187", "311009700", '

# null value to parse 
missing_ssvids <- ""
```

```{r voyages all, echo=F, warning=F, include=FALSE}

voyages_q <- readr::read_file(here::here("queries","proactive", "recent_country_activity_c2_v4.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    missing_ssvids = missing_ssvids,
                                                    start_year = start_year,
                                                    end_year = end_year,
                                                    temp_table = temp_table_voyages,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)

```

```{r voyages ais coverage, echo=F, warning=F, include=FALSE}

ais_cov_q <- readr::read_file(here::here("queries","proactive", "voyage_ais_coverage_no_port.sql"))

# # set parameters for the in-dock area of a port in tema
# port_lat_min <- 5.629
# port_lat_max <- 5.640
# port_lon_min <- 0.0114
# port_lon_max <- 0.01978
# 
# # set parameters for the in-dock area of a port in takoradi
# port_lat_min2 <- 4.885
# port_lat_max2 <- 4.888
# port_lon_min2 <- -1.745
# port_lon_max2 <- -1.7355

voyages_with_coverage <- fishwatchr::gfw_query(query = glue::glue(ais_cov_q, 
                                                    temp_table = temp_table_voyages,
                                                    start_date = start_date,
                                                    end_date = end_date),
                                 run_query = TRUE,
                                 con = con)$data

```

```{r add gfw hyperlink for voyage, echo=F, warning=F, include=FALSE}

# base componenets for VV string to accompany port profiles 
base_string_p1 <- 'https://globalfishingwatch.org/map/vessel/'
base_string_p2 <- '?&start='
base_string_p3 <- '&end='
start_date_url <- '2025-01-01'
end_date_url <- '2025-3-31'

#format(voyages_with_coverage$trip_start, format='%Y-%m-%d')

# paste string components together using vessel id, trip start and trip end from data 
voyages_url <- bind_cols(voyages_with_coverage, 
                         vv_url = paste('=HYPERLINK("',
                          base_string_p1,
                          voyages_with_coverage$vessel_id, 
                          base_string_p2, 
                          as.Date(format(voyages_with_coverage$trip_start, format='%Y-%m-%d'))-2, 
                          base_string_p3, 
                          as.Date(format(voyages_with_coverage$trip_end, format='%Y-%m-%d'))+2,
                          '")', sep=''))

```


```{r add in port information for Ghana using anchorage stops}
# s2ids for port features of interest 
general_port <- c("102078b1", "102078bb", "102078a5", "102078a3", "102078bd", "10207899")
fuel <- c("102078bf")
fishing_port <- c("102078b7", "102078c7", "102078b9")
takoradi_gen <- c("0fe770a9", "0fe770a7", "0fe770a1", "0fe770a3", "0fe770a5", "0fe770af")

# add logic column to indicate presence at each location of interest 
voyages_url$tema_general <- sapply(voyages_url$stop_anchorage_ids, function(x) {
  any(strsplit(x, ",\\s*")[[1]] %in% general_port)
})

voyages_url$tema_fuel <- sapply(voyages_url$stop_anchorage_ids, function(x) {
  any(strsplit(x, ",\\s*")[[1]] %in% fuel)
})

voyages_url$tema_fishing <- sapply(voyages_url$stop_anchorage_ids, function(x) {
  any(strsplit(x, ",\\s*")[[1]] %in% fishing_port)
})

voyages_url$takoradi_general <- sapply(voyages_url$stop_anchorage_ids, function(x) {
  any(strsplit(x, ",\\s*")[[1]] %in% takoradi_gen)
})

```

```{r format the data to TMT format, echo=F, warning=F, include=FALSE}
# change colnames to be sensible for an externally shared document 
voyages_reformat <- dplyr::select(voyages_url, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, AIS_Flag= mmsi_flag, imo, vessel_class_cat=vessel_class_initial, vessel_class_confidence = class_confidence_initial, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, tema_general, tema_fuel, tema_fishing, takoradi_general, fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, percent_ais_voyage=percent_ais_voyage, vv_url)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
voyages_reformat$encounter <- ifelse(is.na(voyages_reformat$num_encounters), FALSE, TRUE)

# overwrite loitering T/F
voyages_reformat$loitering <- ifelse(is.na(voyages_reformat$num_loitering), FALSE, TRUE)

# overwrite fishing T/F
voyages_reformat$fishing <- ifelse(is.na(voyages_reformat$fishing), FALSE, TRUE)

# overwrite fishing_hs T/F
voyages_reformat$fishing_hs <- ifelse(is.na(voyages_reformat$fishing_hs), FALSE, TRUE)

write.csv(voyages_reformat, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),".csv", sep='')), row.names=F)
```

```{r format the data to TMT format, echo=F, warning=F, include=FALSE}
# pull in TMT review data from Matt
tmt_gha <- read.csv(here::here("data","2025_q1", "TMT_feedback", "GHANA - Q1 2025.csv"), header=T)

# make MMSI character for joining 
tmt_gha$MMSI <- as.character(tmt_gha$MMSI)

# standardise gear changes 
gear_changes <- filter(tmt_gha, Gear_type != "")
gear_changes$Gear_type[gear_changes$Gear_type == "Tuna purse seine"] <- "tuna_purse_seines"
gear_changes$Gear_type[gear_changes$Gear_type == "Trawl"] <- "trawlers"
gear_changes$Gear_type[gear_changes$Gear_type == "Drifting longline"] <- "drifting_longlines"

# join on MMSI replace if needed 
gear_corrected <- voyages_reformat %>%
  left_join(
    gear_changes %>% 
      select(MMSI, Gear_type) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(vessel_type = ifelse(!is.na(Gear_type), Gear_type, vessel_type)) %>%
  select(-Gear_type)

# standardise type changes 
ves_changes <- filter(tmt_gha, vessel_class == "other")
ves_changes$Master_type[ves_changes$Master_type == "Refrigerated Cargo Ship"] <- "carrier"
ves_changes$Master_type[ves_changes$Master_type == "Fishing vessel"] <- "fishing"

# join on MMSI replace if needed 
class_corrected <- gear_corrected %>%
  left_join(
      ves_changes %>% 
      select(MMSI, Master_type) %>%
      distinct(MMSI, .keep_all = TRUE),  
    by = "MMSI") %>%
  mutate(vessel_class  = ifelse(!is.na(Master_type), Master_type, vessel_class)) %>%
  select(-Master_type)

# examine new vessels added with code change 
new_ves <- filter(voyages_reformat, !MMSI %in% tmt_gha$MMSI)
# ARGOS REEFER looks genuine others should drop out 

# manual addition of missing vessel
extra <- data.frame("ATLANTIC GLORY", "312864000", "Belize", "Belize", "8919403", "Fishing","high",  "Fishing", "tuna_purse_seines", "CIV", "ABIDJAN", as.POSIXct("2025-03-20 08:26:00", format = "%Y-%m-%d %H:%M:%S"), "4", as.POSIXct("2025-03-21 09:00:00", format = "%Y-%m-%d %H:%M:%S"), "4", "1","TEMA", FALSE, FALSE, TRUE, FALSE, FALSE, NA, NA, FALSE, NA, FALSE, 0, FALSE, 0, 100, "")
colnames(extra) <- colnames(class_corrected)

additions <- rbind(class_corrected, extra)

# drop out vessels that aren't relevant 
final_list <- filter(additions,  !MMSI %in% filter(tmt_gha, Relevant=="Don’t use")$MMSI) 

# drop out container reefers
final_list_v2 <- filter(final_list,  !MMSI %in% c('311000958', '566341000', 
                                                  '636013068','636014240', '311000876', 
                                                  '636014241', '563237900', '636013073',
                                                  '563229800')) 

write.csv(final_list_v2, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),"_v2.csv", sep='')), row.names=F)
```

```{r GHA graphs, echo=F, warning=F, include=FALSE}
install.packages("viridis")
library(viridis)

# flag pie chart 
final_list_v2$Flag  <- final_list_v2$AIS_Flag 

data <- final_list_v2 %>%
  group_by(Flag) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(Flag, "\n", vessels)
  )

ggplot(data, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = Flag)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  #scale_fill_viridis(option="plasma", discrete=TRUE)+
  theme(legend.position = "none") +
  geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  ggtitle("Ghana voyages by flag")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "ghana_fishing_flags_",str_replace_all(Sys.Date(), '-','_'),"v2.png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')

#------------------------------------------------------
# Vessel class pie chart  
library(ggrepel)

final_list_v2$vessel_class[final_list_v2$vessel_class=='Fishing'] <- 'fishing'

plot_dat <- final_list_v2 %>%
  group_by(vessel_class) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_class, "\n", vessels)
  ) 

ggplot(plot_dat, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_class)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  ggtitle("Ghana voyages by type")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "vessel_class_",str_replace_all(Sys.Date(), '-','_'),"v2.png")), 
       units = 'cm', 
       width = 7, 
       height = 7,
       bg = '#f7f7f7')


#------------------------------------------------------
# Vessel type pie chart  
final_list_v2$vessel_type[final_list_v2$vessel_type=='other'] <- 'carrier'

plot_dat <- final_list_v2 %>%
  group_by(vessel_type) %>%
  summarize(vessels = n()) %>%
    mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_type, "\n", vessels)
  ) 

ggplot(plot_dat, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_type)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  ggtitle("Ghana voyages by gear")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_gears_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')


```

# Senegal  

# set parameters for analysis 

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2025-01-01 00:00:00 UTC'" 
end_date <- "'2025-03-31 23:59:59 UTC'"
year <- 2025

country_iso3 <- "'SEN'"
port_name <- "'DAKAR'"

# file names
month <- 'Q1'
country <- 'SEN'


missing_ssvids <- '"630123009", "306881000", "412209113", "663250000"'

# create a temp table for query 
temp_table_voyages <- '`world-fishing-827.scratch_max.sen_q1_25_all_voyages_temp`'
```

```{r voyages all, echo=F, warning=F, include=FALSE}

voyages_q <- readr::read_file(here::here("queries","proactive", "recent_country_activity_c2_v4.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    start_year = start_year,
                                                    end_year = end_year,
                                                    temp_table = temp_table_voyages,
                                                    missing_ssvids = missing_ssvids,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)

```

```{r voyages ais coverage, echo=F, warning=F, include=FALSE}

ais_cov_q <- readr::read_file(here::here("queries","proactive", "voyage_ais_coverage_no_port.sql"))

# set parameters for the in-dock area of a port in Abidjan
# port_lat_min <- 14.681
# port_lat_max <- 14.689
# port_lon_min <- -17.435
# port_lon_max <- -17.429

voyages_with_coverage <- fishwatchr::gfw_query(query = glue::glue(ais_cov_q, 
                                                    temp_table = temp_table_voyages,
                                                    start_date = start_date,
                                                    end_date = end_date),
                                 run_query = TRUE,
                                 con = con)$data

```

```{r add gfw hyperlink for voyage, echo=F, warning=F, include=FALSE}

# base componenets for VV string to accompany port profiles 
base_string_p1 <- 'https://globalfishingwatch.org/map/vessel/'
base_string_p2 <- '?&start='
base_string_p3 <- '&end='
start_date_url <- '2025-01-01'
end_date_url <- '2025-3-31'

#format(voyages_with_coverage$trip_start, format='%Y-%m-%d')

# paste string components together using vessel id, trip start and trip end from data 
voyages_url <- bind_cols(voyages_with_coverage, 
                         vv_url = paste('=HYPERLINK("',
                          base_string_p1,
                          voyages_with_coverage$vessel_id, 
                          base_string_p2, 
                          as.Date(format(voyages_with_coverage$trip_start, format='%Y-%m-%d'))-2, 
                          base_string_p3, 
                          as.Date(format(voyages_with_coverage$trip_end, format='%Y-%m-%d'))+2,
                          '")', sep=''))

```


```{r add in port information for SEN using anchorage stops}
anchorages <- fishwatchr::gfw_query(query = c("SELECT s2id, label, sublabel FROM `world-fishing-827.anchorages.named_anchorages_v20240117` WHERE iso3 = 'SEN'"),
                       run_query = TRUE,
                       con = con)$data

table(anchorages$sublabel)

# s2ids for port features of interest 
general <- c("0ec17253", "0ec173ad", "0ec173b3", "0ec173b1", "0ec173af", "0ec173a9")
fishing <- c("0ec17301", "0ec173ab", "0ec172ff", "0ec17255")

port_stops <- voyages_url %>%
  rowwise() %>%
  mutate(dak_general = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% general),
         dak_fishing = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% fishing))

```


```{r format the data to TMT format, echo=F, warning=F, include=FALSE}
# change colnames to be sensible for an externally shared document 
voyages_reformat <- dplyr::select(port_stops, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, flag_ais=mmsi_flag, imo, vessel_class_cat=vessel_class_initial, vessel_class_confidence = class_confidence_initial, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, dak_general, dak_fishing, fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, percent_ais_voyage=percent_ais_voyage, vv_url)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
voyages_reformat$encounter <- ifelse(is.na(voyages_reformat$num_encounters), FALSE, TRUE)

# overwrite loitering T/F
voyages_reformat$loitering <- ifelse(is.na(voyages_reformat$num_loitering), FALSE, TRUE)

# overwrite fishing T/F
voyages_reformat$fishing <- ifelse(is.na(voyages_reformat$fishing), FALSE, TRUE)

# overwrite fishing_hs T/F
voyages_reformat$fishing_hs <- ifelse(is.na(voyages_reformat$fishing_hs), FALSE, TRUE)

write.csv(voyages_reformat, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),".csv", sep='')), row.names=F)
```

```{r update the data based on TMT review Senegal, echo=F, warning=F, include=FALSE}
# pull in TMT review data from Matt
tmt_sen <- read.csv(here::here("data","2025_q1", "TMT_feedback", "DAKAR- Q1 2025.csv"), header=T)

# make MMSI character for joining 
tmt_sen$MMSI <- as.character(tmt_sen$MMSI)

# drop rows with action to remove identify rows to drop 
tmt_sen_drop <- tmt_sen %>% filter(str_detect(Action, "REMOVE"))
tmt_sen_ret <- tmt_sen %>% filter(!str_detect(Action, "REMOVE"))

# standardise gear changes 
gear_changes <- filter(tmt_sen_ret, Gear.type != "")

gear_corrected <- voyages_reformat %>%
  left_join(
    gear_changes %>%
      select(MMSI, new_vt = vessel_type) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(vessel_type = ifelse(!is.na(new_vt), new_vt, vessel_type)) %>%
  select(-new_vt)

# standardise use of fishing and unknown
gear_corrected$vessel_type[gear_corrected$vessel_type %in% c('fishing')] <- 'unknown'


# standardise type changes 
type_changes <- filter(tmt_sen_ret, Vessel.type != "")

type_corrected <- gear_corrected %>%
  left_join(
    type_changes %>%
      select(MMSI, new_vc = vessel_class) %>%
      distinct(MMSI, .keep_all = TRUE),
    by = "MMSI") %>%
  mutate(vessel_class = ifelse(!is.na(new_vc), new_vc, vessel_class)) %>%
  select(-new_vc)

# manual override for incomplete values 
type_corrected$vessel_class[type_corrected$vessel_class %in% c('other','seismic_vessel','cargo','gear')] <- 'fishing'

# mannually correct vessel name 
type_corrected$vessel_name[type_corrected$MMSI == '412440842'] <- 'FU YUAN YU 7857'
type_corrected$vessel_name[type_corrected$MMSI == '412201826'] <- 'SHENG HAI 3'


# # examine new vessels added with code change 
new_ves <- filter(voyages_reformat, !MMSI %in% tmt_sen$MMSI)
# no new vessels

# # manual addition of missing vessel
extra <- data.frame("ARTIKE", "306881000", "CUW", "CUW", "9808120", "Fishing","high",  "support", "purse_seine_support", "CIV", "ABIDJAN", as.POSIXct("2025-03-08 08:02:00", format = "%Y-%m-%d %H:%M:%S"), "4", as.POSIXct("2025-03-20 11:00:00", format = "%Y-%m-%d %H:%M:%S"), "4", "12","DAKAR", FALSE, FALSE, FALSE, NA, NA, FALSE, NA, FALSE, 0, FALSE, 0, 75, "")
colnames(extra) <- colnames(type_corrected)

additions <- data.frame(rbind(type_corrected, extra))
# 
# # drop out vessels that aren't relevant 
# final_list <- filter(class_corrected,  MMSI %in% filter(tmt_gha, Relevant=="Use")$MMSI) 

# remove vessels from TMT review saying drop 
plot_df_sen <-  filter(additions, !MMSI %in% unique(tmt_sen_drop$MMSI))

write.csv(plot_df_sen, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),"_v2.csv", sep='')), row.names=F)
```

```{r SEN graphs, echo=F, warning=F, include=FALSE}
# flag pie chart 
data <- plot_df_sen %>%
  group_by(Flag) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(Flag, "\n", vessels)
  )

ggplot(data, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = Flag)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  #scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  #scale_fill_viridis(option="plasma", discrete=TRUE)+
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 2.5,
    nudge_x = 0.5,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Senegal voyages by Flag")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_flags-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')

#------------------------------------------------------
# Vessel class pie chart  
plot_dat_class <- plot_df_sen %>%
  group_by(vessel_class) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_class, "\n", vessels)
  ) 

ggplot(plot_dat_class, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_class)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 3,
    nudge_x = 0.3,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Senegal voyages \n by vessel type")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "vessel_class-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 7, 
       height = 7,
       bg = '#f7f7f7')


#------------------------------------------------------
# Vessel type pie chart  
plot_dat <- plot_df_sen %>%
  group_by(vessel_type) %>%
  summarize(vessels = n()) %>%
    mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_type, "\n", vessels)
  ) 

ggplot(plot_dat, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_type)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 2.5,
    nudge_x = 0.5,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Senegal voyages by gear")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_gears-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')


```


```{r SEN pull in the fishing data, echo=F, warning=F, include=FALSE}

q_confidence <- readr::read_file(here::here("queries","proactive", "proactive_fishing_locations.sql"))

fishing <- fishwatchr::gfw_query(query = glue::glue(q_confidence,
                                               voyages_table = "`world-fishing-827.scratch_max.sen_q1_25_all_voyages_temp`" 
                                               ),
                                 run_query = TRUE,
                                 con = con)$data

# sense check the data 
fishing %>%
    group_by(ssvid) %>%
      summarise(positions = n(), 
                min_date = min(event_start), 
                max_date = max(event_end))

# add gear from TMT review 
gear <- distinct(dplyr::select(plot_df_sen, MMSI, Flag, vessel_type)) %>% 
  mutate(ssvid=as.character(MMSI))

fishing_data <- left_join(fishing, gear, by = join_by(ssvid))


```

```{r SEN voyage activity longline maps, echo=F, warning=F, include=FALSE}

# bin the data
fishing_data$lat_bin <- round(fishing_data$lat_mean/0.5)*0.5
fishing_data$lon_bin <- round(fishing_data$lon_mean/0.5)*0.5

table(fishing_data$vessel_type)

# count positions in each lat lon bin
longline_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, vessel_type %in% c('drifting_longlines')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 500 
#set plot center 
new_center <- 40

# 
quantile(longline_raster$fishing_hours)

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=40 +wktext"

# set plot limits bound on the data
bounding_atl <- transform_box(xlim = c(-45, 0),
                          ylim = c(15, -15),
                          output_crs = best_proj)

# map for atlantic longline 
atl_full <- longline_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atl$box_out[['xmin']], bounding_atl$box_out[['xmax']]),
      ylim = c(bounding_atl$box_out[['ymin']], bounding_atl$box_out[['ymax']]),
      crs = bounding_atl$out_crs) +
    # scale_x_continuous(breaks = custom_breaks, labels = custom_labels)+
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light') +
    theme(legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 6),
        legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 6),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(2, 'mm'),
      legend.key.width = unit(15,'mm'))


fishwatchr::add_little_globe(atl_full,
                             main_box = bounding_atl,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures','q1_25_proactive', paste0(country,"_", month,"_", "longline_map-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 15, 
       height = 17,
       bg = '#f7f7f7')

```


```{r SEN voyage activity trawl maps, echo=F, warning=F, include=FALSE}
# add a different lat lon bin 
fishing_data$lat_bin <- round(fishing_data$lat_mean/0.1)*0.1
fishing_data$lon_bin <- round(fishing_data$lon_mean/0.1)*0.1


# count positions in each lat lon bin
trawl_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, vessel_type %in% c('trawlers')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 9000 
#set plot center 
new_center <- 17

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=17 +wktext"

# set plot limits bound on the data
bounding_wa <- transform_box(xlim = c(-20, -14),
                          ylim = c(16, 8.5),
                          output_crs = best_proj)

# trawl map 
trawl_full <- trawl_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_wa$box_out[['xmin']], bounding_wa$box_out[['xmax']]),
      ylim = c(bounding_wa$box_out[['ymin']], bounding_wa$box_out[['ymax']]),
      crs = bounding_wa$out_crs) +
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light')  +
    theme(legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 6),
        legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 6),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(2, 'mm'),
      legend.key.width = unit(15,'mm'))


fishwatchr::add_little_globe(trawl_full,
                             main_box = bounding_wa,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "trawl_map-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 15, 
       height = 17,
       bg = '#f7f7f7')

```



# Kenya  

# set parameters for analysis 

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2025-01-01 00:00:00 UTC'" 
end_date <- "'2025-03-31 23:59:59 UTC'"
year <- 2025

country_iso3 <- "'KEN'"
#port_name <- "'MOMBASA'"

# file names
month <- 'Q1'
country <- 'KEN'

# create a temp table for query 
temp_table_voyages <- '`world-fishing-827.scratch_max.ken_q1_25_all_voyages_temp`'
```

```{r voyages all, echo=F, warning=F, include=FALSE}

voyages_q <- readr::read_file(here::here("queries","proactive", "recent_country_activity_c2_v4.sql"))

fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    start_year = start_year,
                                                    end_year = end_year,
                                                    temp_table = temp_table_voyages,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)

```

```{r voyages ais coverage, echo=F, warning=F, include=FALSE}

ais_cov_q <- readr::read_file(here::here("queries","proactive", "voyage_ais_coverage_no_port.sql"))

# set parameters for the in-dock area of a port in Abidjan
# port_lat_min <- -4.071
# port_lat_max <- -4.0686
# port_lon_min <- 39.656
# port_lon_max <- 39.658

voyages_with_coverage <- fishwatchr::gfw_query(query = glue::glue(ais_cov_q, 
                                                    temp_table = temp_table_voyages,
                                                    start_date = start_date,
                                                    end_date = end_date),
                                 run_query = TRUE,
                                 con = con)$data

```

```{r add gfw hyperlink for voyage, echo=F, warning=F, include=FALSE}

# base componenets for VV string to accompany port profiles 
base_string_p1 <- 'https://globalfishingwatch.org/map/vessel/'
base_string_p2 <- '?&start='
base_string_p3 <- '&end='
start_date_url <- '2025-01-01'
end_date_url <- '2025-3-31'

#format(voyages_with_coverage$trip_start, format='%Y-%m-%d')

# paste string components together using vessel id, trip start and trip end from data 
voyages_url <- bind_cols(voyages_with_coverage, 
                         vv_url = paste('=HYPERLINK("',
                          base_string_p1,
                          voyages_with_coverage$vessel_id, 
                          base_string_p2, 
                          as.Date(format(voyages_with_coverage$trip_start, format='%Y-%m-%d'))-2, 
                          base_string_p3, 
                          as.Date(format(voyages_with_coverage$trip_end, format='%Y-%m-%d'))+2,
                          '")', sep=''))

```



```{r add in port information for SEN using anchorage stops}
anchorages <- fishwatchr::gfw_query(query = c("SELECT s2id, lat, lon, label, sublabel FROM `world-fishing-827.anchorages.named_anchorages_v20240117` WHERE iso3 = 'KEN'"),
                       run_query = TRUE,
                       con = con)$data

table(anchorages$sublabel)

# write.csv(anchorages, here::here("data","2025_q1", paste(country,'anchorages-', Sys.Date(),".csv", sep='')), row.names=F)


# s2ids for port features of interest 
general <- c("18401349", "18401347",  "18406d2b", "18406d31", 
             "18406d13", "18406d6b", "18406d15", "18406d2d", "18406d41", "18406d47", 
             "18406d37", "18406d33", "18406d49", "18406d0d")
fishing <- c("18401331", "1840132d")
dry_dock <- c("18401337","18401339")
fish_harbour <- c("18406cd3", "18406ccd" , "18406ccf",  "18406cd1")
harbor <- c("18406d0f", "18406da9", "18406d07", "18406daf", "18406d09", "18406da7",
            "18406cd7", "18406d2f", "18406d29")


port_stops <- voyages_url %>%
  rowwise() %>%
  mutate(mom_general = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% general),
         mom_fishing = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% fishing),
         mom_fishing_harbor = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% fish_harbour),
         mom_drydock = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% dry_dock),
         mom_harbor = any(str_trim(str_split(stop_anchorage_ids, ",")[[1]]) %in% harbor))

```


```{r format the data to TMT format, echo=F, warning=F, include=FALSE}
# change colnames to be sensible for an externally shared document 
voyages_reformat <- dplyr::select(port_stops, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, imo, vessel_class_cat=vessel_class_initial, vessel_class_confidence = class_confidence_initial, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, mom_general, mom_fishing, mom_fishing_harbor, mom_harbor, mom_drydock,  fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, percent_ais_voyage=percent_ais_voyage, vv_url)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
voyages_reformat$encounter <- ifelse(is.na(voyages_reformat$num_encounters), FALSE, TRUE)

# overwrite loitering T/F
voyages_reformat$loitering <- ifelse(is.na(voyages_reformat$num_loitering), FALSE, TRUE)

# overwrite fishing T/F
voyages_reformat$fishing <- ifelse(is.na(voyages_reformat$fishing), FALSE, TRUE)

# overwrite fishing_hs T/F
voyages_reformat$fishing_hs <- ifelse(is.na(voyages_reformat$fishing_hs), FALSE, TRUE)

# write.csv(voyages_reformat, here::here("data","2025_q1", paste(country,'_', month,'_', year,'_', Sys.Date(),".csv", sep='')), row.names=F)
```


```{r update the data based on TMT review Kenya, echo=F, warning=F, include=FALSE}
# pull in TMT review data from Matt
tmt_ken <- read.csv(here::here("data","2025_q1", "TMT_feedback", "KEN - Q1 2025.csv"), header=T)

table(tmt_ken$Action)

# make MMSI character for joining 
tmt_ken$MMSI <- as.character(tmt_ken$MMSI)

# drop rows with action to remove identify rows to drop 
tmt_ken_drop <- tmt_ken %>% filter(str_detect(Action, "Remove"))

plot_df_ken <-  filter(voyages_reformat, !MMSI %in% unique(tmt_ken_drop$MMSI))

# update incorrect vessel class 
plot_df_ken$vessel_class[plot_df_ken$vessel_class == 'passenger'] <- "fishing"

# update vessel gear
plot_df_ken$vessel_type[plot_df_ken$MMSI %in% c("412460035")] <- "unknown_set_gear"
plot_df_ken$vessel_type[plot_df_ken$MMSI %in% c("412411792", "412411789", "412411788", "412411791")] <- "unknown_set_gear"
plot_df_ken$vessel_type[plot_df_ken$vessel_type == 'passenger'] <- "longline"

# manually create extra df rows for port visits to non-designated anchorages 
extra <- data.frame(tibble(
  vessel_name = c("XING WANG 805", "ZONG YANG 36", "ZONG YANG 38"),
  MMSI = c("412411791", "412460034", "412460035"),
  Flag = c("CHN", "CHN", "CHN"),
  imo = c("8549961", "9753478", "9753480"),
  vessel_class_cat = c("Fishing", "Fishing", "Fishing"),
  vessel_class_confidence = c("high", "high", "high"),
  vessel_class = c("fishing", "fishing", "fishing"),
  vessel_type = c("unknown_set_gear", "unknown_set_gear", "unknown_set_gear"),
  previous_port_country = c("KEN", "KEN", "KEN"),
  previous_port = c("MOMBASA", "MOMBASA", "MOMBASA"),
  trip_start = as.POSIXct(c("2025-02-24 14:20:00", "2025-03-14 13:33:00", "2025-02-22 12:31:00")),
  trip_start_confidence = c(4, 4, 4),
  trip_end = as.POSIXct(c("2025-03-09 17:00:00", "2025-03-25 07:00:00", "2025-02-26 07:00:00")),
  trip_end_confidence = c(2, 2, 2),
  trip_duration_days = c(13, 11, 4),
  end_port = c("LAMU", "KILIFI", "KILIFI"),
  mom_general = c(FALSE, FALSE, FALSE),
  mom_fishing = c(FALSE, FALSE, FALSE),
  mom_fishing_harbor = c(FALSE, FALSE, FALSE),
  mom_harbour = c(FALSE, FALSE, FALSE),
  mom_drydock = c(FALSE, FALSE, FALSE),
  fishing = c(TRUE, TRUE, TRUE),
  fishing_hours = c(NA, 40, 15),
  fishing_eez = c("SOM", "KEN", "KEN"),
  fishing_hs = c(FALSE, FALSE, FALSE),
  fishing_rfmos = c(NA, NA, NA),
  encounter = c(FALSE, FALSE, FALSE),
  num_encounters = c(0, 0, 0),
  loitering = c(FALSE, FALSE, FALSE),
  num_loitering = c(0, 0, 0),
  percent_ais_voyage = c(11, 20, 18),
  vv_url = c("", "", "")
))

# add new rows to existing dataframe
additions <- bind_rows(plot_df_ken, extra)

write.csv(additions, here::here("data","2025_q1", paste(country,'_', month,'_', year,'-', Sys.Date(),"_v2.csv", sep='')), row.names=F)
```

```{r KEN graphs, echo=F, warning=F, include=FALSE}
# flag pie chart 
data <- additions %>%
  group_by(Flag) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(Flag, "\n", vessels)
  )

ggplot(data, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = Flag)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  #scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  #scale_fill_viridis(option="plasma", discrete=TRUE)+
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 2.5,
    nudge_x = 0.5,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Kenya voyages by Flag")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_flags-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')


# Vessel class pie chart  
plot_dat_class <- additions %>%
  group_by(vessel_class) %>%
  summarize(vessels = n()) %>%
  mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_class, "\n", vessels)
  ) 

ggplot(plot_dat_class, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_class)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 3,
    nudge_x = 0.3,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Kenya voyages \n by vessel type")


ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "vessel_class-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 7, 
       height = 7,
       bg = '#f7f7f7')


# Vessel type pie chart 
plot_dat <- additions %>%
  group_by(vessel_type) %>%
  summarize(vessels = n()) %>%
    mutate(
    fraction = vessels / sum(vessels),
    ymax = cumsum(fraction),
    ymin = lag(ymax, default = 0),
    label = paste0(vessel_type, "\n", vessels)
  ) 

ggplot(plot_dat, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = vessel_type)) +
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  scale_fill_manual(values=gfw_palettes[['tracks']]) + 
  theme(legend.position = "none") +
  # geom_text(x = 3.5, aes(y = (ymin + ymax)/2, label = label), size = 3) +
  geom_text_repel(
    aes(x = 3.5, y = (ymin + ymax)/2, label = label),
    size = 2.5,
    nudge_x = 0.5,
    segment.color = "grey50",   # optional: draws a line from label to pie
    show.legend = FALSE,
    direction = "y",
    force = 1,
    max.overlaps = 20
  ) +
  ggtitle("Kenya voyages by gear")

ggsave( filename = here::here('outputs', 'figures', 'q1_25_proactive', paste0(country,"_", month,"_", "fishing_gears-",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')


```
