---
title: "Recent port activity of Port Program pilot countries"
author: "Max Schofield"
date: "2023-11-14"
output:
  html_document:
    df_print: paged
  df_print: default
  html_notebook: null
highlight: pygments
toc: yes
toc_float:
  toc_collapsed: yes
toc_depth: 2
editor_options:
  chunk_output_type: inline
---

```{=html}
<style>
body {
text-align: left}
</style>
```

# Setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=F, warning=F, include=FALSE}
load_or_install_libraries <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
load_or_install_libraries( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rgeos", "ggspatial") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)

# if (!require("extrafont"))
#   install.packages("extrafont")

# # Unfortunately `extrafont::font_import()` will fail on latest Rttf2pt1 package...
# # so we need to install old version
# devtools::install_version("Rttf2pt1", version = "1.3.8")
# 
# # Import fonts to R
# # This will take few minutes
# extrafont::font_import()

# remove a package causing issues 
#detach("package:plyr", unload=TRUE)
```

```{r connection to BQ, echo=F, warning=F, include=FALSE}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```

# Dakar 

```{r set date and port parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2024-07-01 00:00:00 UTC'" 
end_date <- "'2024-09-30 23:59:59 UTC'"
year <- 2024
country_iso3 <- "'SEN'"
port_name <- "'DAKAR'"

# file names
month <- 'Q3'
country <- 'SEN'

```

```{r voyages all, echo=F, warning=F, include=FALSE}

voyages_q <- readr::read_file(here::here("queries","proactive", "recent_port_activity_c2_v3.sql"))

voyages <- fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    port_label = port_name,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)$data

# check the vessels that work and don't 
unique(filter(voyages, ssvid %in% c("308121000", "629009092", "629009118", "227550000", "412300004", "412549434", "352545000", "355855000", "224546000", "412209012", "312507000"))$ssvid)


```


```{r make vessel viewer url string}
base_string_p1 <- 'https://globalfishingwatch.org/map/vessel/'
base_string_p2 <- '?&start=' 
base_string_p3 <- '&end='
start_date_url <- '2024-09-01'
end_date_url <- '2024-10-31'

voyages_url <- bind_cols(voyages, vv_url = paste('=HYPERLINK("',base_string_p1, voyages_sample$vessel_id, base_string_p2, start_date_url, base_string_p3, end_date_url, '")', sep=''))

```

```{r groom data to TMT format}
dak_voyages <- dplyr::select(voyages_url, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, vessel_id=vessel_id, trip_id=trip_id, vv_url)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
dak_voyages$encounter <- ifelse(is.na(dak_voyages$num_encounters), FALSE, TRUE)

# overwrite fishing T/F
dak_voyages$loitering <- ifelse(is.na(dak_voyages$num_loitering), FALSE, TRUE)

# overwrite loitering T/F
dak_voyages$fishing <- ifelse(is.na(dak_voyages$fishing), FALSE, TRUE)

# overwrite loitering T/F
#dak_voyages$gaps <- ifelse(is.na(dak_voyages$num_gaps), FALSE, TRUE)

dak_voyages$fishing_hs <- ifelse(is.na(dak_voyages$fishing_hs), FALSE, TRUE)

```


```{r voyages extra as queries cant link up, echo=F, warning=F, include=FALSE}

extra <- fishwatchr::gfw_query(query = c("SELECT * FROM `world-fishing-827.scratch_max.aiscoverage_dakar_2024-q2_pipe25`"),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r final r manipulation}

full_dak_info <- left_join(dak_voyages, dplyr::select(extra,vessel_id, trip_id, at_dock, percent_ais_voyage), by=c('vessel_id','trip_id'))

write.csv(dplyr::select(dak_voyages,-vessel_id, -trip_id), here::here("data", "dakar_Q3_2024_16Oct2024.csv"), row.names=F)
```


```{r pull in TMT data make figures}
tmt_review <- read.csv(here::here("data","proactive", "dakar_Q1_2024_19Apr2024_tmt_review.csv"), header=T)

# drop rows which TMT identified to be removed 
tmt_review$Remove.or.check[tmt_review$Remove.or.check==""] <- NA
tmt_review$Remove.or.check[grepl("^Remove", tmt_review$Remove.or.check)] <- 'Remove'
tmt_review$Remove.or.check[grepl("^Check", tmt_review$Remove.or.check)] <- 'Check'

tmt_review_v2 <- filter(tmt_review, Remove.or.check != 'Remove' | is.na(Remove.or.check))

#### correct vessel type #### 
tmt_review_v2$Incorrect...missing.vessel.type[tmt_review_v2$Incorrect...missing.vessel.type==""] <- NA

# set names for vessel type to same levels existing 
table(tmt_review_v2$Incorrect...missing.vessel.type)
tmt_review_v2$Incorrect...missing.vessel.type[tmt_review_v2$Incorrect...missing.vessel.type=='Fishing vessel'] <- 'fishing'
tmt_review_v2$Incorrect...missing.vessel.type[tmt_review_v2$Incorrect...missing.vessel.type=='Reefer'] <- 'carrier'
tmt_review_v2$Incorrect...missing.vessel.type[tmt_review_v2$Incorrect...missing.vessel.type=='Support vessel'] <- 'support'
table(tmt_review_v2$Incorrect...missing.vessel.type)

tmt_review_v2$vessel_class[!is.na(tmt_review_v2$Incorrect...missing.vessel.type)] <- tmt_review_v2$Incorrect...missing.vessel.type[!is.na(tmt_review_v2$Incorrect...missing.vessel.type)] 

table(tmt_review_v2$vessel_class)
# still some seismic_vessels to correct with missing data from TMT 
tmt_review_v2$vessel_class[tmt_review_v2$vessel_class=='seismic_vessel'] <- 'fishing'
tmt_review_v2$vessel_class[tmt_review_v2$vessel_class=='other'] <- 'fishing'
table(tmt_review_v2$vessel_class)

####----------------------------------------------------------------------------
#### correct vessel class #### 
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear==""] <- NA
# set names for vessel type to same levels existing 
table(tmt_review_v2$Incorrect...missing.gear)
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Longline'] <- 'fishing'
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Pole and line'] <- 'pole_and_line'
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Trawler '] <- 'trawlers'
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Trawler'] <- 'trawlers'
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Purse seine'] <- 'tuna_purse_seines'
tmt_review_v2$Incorrect...missing.gear[tmt_review_v2$Incorrect...missing.gear=='Longline'] <- 'longliners'
table(tmt_review_v2$Incorrect...missing.gear)


tmt_review_v2$vessel_type[!is.na(tmt_review_v2$Incorrect...missing.gear)] <- tmt_review_v2$Incorrect...missing.gear[!is.na(tmt_review_v2$Incorrect...missing.gear)]
table(tmt_review_v2$vessel_type)

# still some manual grooming 
tmt_review_v2$vessel_type[tmt_review_v2$vessel_type=='other'] <- 'fishing'

# set to vessel class when inconclusive
tmt_review_v2$vessel_type[tmt_review_v2$vessel_type=='inconclusive'] <- tmt_review_v2$vessel_class
table(tmt_review_v2$vessel_type)

#####---------------------------------------------------------------------------
#### correct Flag #### 
tmt_review_v2$Incorrect...missing.flag[tmt_review_v2$Incorrect...missing.flag==""] <- NA
tmt_review_v2$Flag[!is.na(tmt_review_v2$Incorrect...missing.flag)] <- tmt_review_v2$Incorrect...missing.flag[!is.na(tmt_review_v2$Incorrect...missing.flag)]
table(tmt_review_v2$Flag)

```
```{r take TMT updates from previous analysis and add them to the current}

# take data corrections from previous review
tmt_review_v2$MMSI <- as.character(tmt_review_v2$MMSI)
correct_gear <- distinct(dplyr::select(filter(tmt_review_v2, !is.na(Incorrect...missing.gear)), MMSI, Incorrect...missing.gear))
add_gear <- left_join(full_dak_info, correct_gear, by='MMSI')
       
correct_type <- distinct(dplyr::select(filter(tmt_review_v2, !is.na(Incorrect...missing.vessel.type)), MMSI, Incorrect...missing.vessel.type))
add_type <- left_join(add_gear, correct_type, by='MMSI')
 
correct_flag <- distinct(dplyr::select(filter(tmt_review_v2, !is.na(Incorrect...missing.flag)), MMSI, Incorrect...missing.flag))
add_flag <- left_join(add_type, correct_flag, by='MMSI')
  
# overwrite data connections from previous Q1 review 
add_flag$Flag[!is.na(add_flag$Incorrect...missing.flag)] <- add_flag$Incorrect...missing.flag[!is.na(add_flag$Incorrect...missing.flag)]
  
add_flag$vessel_class[!is.na(add_flag$Incorrect...missing.vessel.type)] <- add_flag$Incorrect...missing.vessel.type[!is.na(add_flag$Incorrect...missing.vessel.type)]
  
add_flag$vessel_type[!is.na(add_flag$Incorrect...missing.gear)] <- add_flag$Incorrect...missing.gear[!is.na(add_flag$Incorrect...missing.gear)]

# write out data 
#write.csv(dplyr::select(add_flag,-"Incorrect...missing.gear", -"Incorrect...missing.vessel.type", -"Incorrect...missing.flag"), here::here("data", "dakar_Q2_2024_16Jul2024.csv"), row.names=F)
```

```{r input reviewed TMT data for q2}
tmt_review_new <- read.csv(here::here("data","proactive", "dakar_Q2_2024_07Aug2024_tmt_review.csv"), header=T)

table(tmt_review_new$Action)

# remove rows marked for remove
tmt_review_new_v2 <- tmt_review_new[tmt_review_new$Action != 'REMOVE', ]

# look at current values for vessel_type
table(tmt_review_new_v2$vessel_type)

## update TMT values to reflect GFW values 
# vessel_class
tmt_review_new_v2$Vessel.type[tmt_review_new_v2$Vessel.type=='Fishing vessel'] <- 'fishing'

# vessel_type
tmt_review_new_v2$Gear.type[tmt_review_new_v2$Gear.type=='Purse seiner'] <- 'tuna_purse_seines'
tmt_review_new_v2$Gear.type[tmt_review_new_v2$Gear.type=='Trawlers'] <- 'trawlers'

#  update check / identity change table
tmt_review_new_v2$vessel_type[tmt_review_new_v2$Action == 'CHECK / IDENTITY CHANGE'][tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'CHECK / IDENTITY CHANGE'] != ""] <- 
tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'CHECK / IDENTITY CHANGE'][tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'CHECK / IDENTITY CHANGE'] != ""]
table(tmt_review_new_v2$vessel_type)

# update name changes 
table(tmt_review_new_v2[tmt_review_new_v2$Action == 'IDENTITY CHANGE', ]$Gear.type)
tmt_review_new_v2$vessel_name

tmt_review_new_v2$vessel_name[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Name[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""] <- 
tmt_review_new_v2$Name[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Name[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""]

# update vessel type
tmt_review_new_v2$vessel_class[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Vessel.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""] <- 
tmt_review_new_v2$Vessel.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Vessel.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""]

# update gear type
tmt_review_new_v2$vessel_type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""] <- 
tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'][tmt_review_new_v2$Gear.type[tmt_review_new_v2$Action == 'IDENTITY CHANGE'] != ""]

# check values
table(tmt_review_new_v2$vessel_class) 
table(tmt_review_new_v2$vessel_type) 

write.csv(dplyr::select(tmt_review_new_v2,-"Incorrect...missing.gear", -"Incorrect...missing.vessel.type", -"Incorrect...missing.flag"), here::here("data", "dakar_Q2_2024_16Jul2024.csv"), row.names=F)

# https://globalfishingwatch.org/map/fishing-activity/vessel_missing_from_q_2_2024_dakar_port_analysis-user-public/vessel/630f3fbd5-5b60-a9f9-264a-bb6d949ba3b2?vesselDatasetId=public-global-vessel-identity%3Av3.0&vesselIdentitySource=selfReportedInfo&vesselSelfReportedId=48b310f78-8edd-e2a3-8b30-722b2ee97cd6&visibleEvents[0]=fishing&visibleEvents[1]=encounter&visibleEvents[2]=port_visit&longitude=-15.893355062108919&latitude=15.393651389957574&zoom=6.141303053718126&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z

#https://globalfishingwatch.org/map/fishing-activity/default-public?latitude=13.573236706543307&longitude=-15.772440969703073&zoom=4.600777145789837&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z&dvIn[0][id]=vessel-818356b57-7844-a4ae-919e-36a06ae5a84a&dvIn[0][dvId]=fishing-map-vessel-track-v-3&dvIn[0][cfg][track]=public-global-all-tracks%3Av3.0&dvIn[0][cfg][info]=public-global-vessel-identity%3Av3.0&dvIn[0][cfg][events][0]=public-global-fishing-events%3Av3.0&dvIn[0][cfg][events][1]=public-global-port-visits-events%3Av3.0&dvIn[0][cfg][events][2]=public-global-encounters-events%3Av3.0&dvIn[0][cfg][events][3]=public-global-loitering-events%3Av3.0&dvIn[0][cfg][events][4]=public-global-gaps-events%3Av3.0&dvIn[0][cfg][clr]=%23F95E5E&dvIn[1][id]=fishing-ais-pipe-3&dvIn[1][cfg][vis]=false&dvIn[2][id]=vms&dvIn[2][cfg][vis]=false&dvIn[3][id]=context-layer-eez&dvIn[3][cfg][vis]=true&lTD=&fTD=&timebarVisualisation=vessel


#https://globalfishingwatch.org/map/fishing-activity/default-public?latitude=13.93585953545746&longitude=-10.4345&zoom=4.0891&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z&dvIn[0][id]=fishing-ais-pipe-3&dvIn[0][cfg][vis]=false&dvIn[1][id]=vms&dvIn[1][cfg][vis]=false&dvIn[2][id]=vessel-1fe43f651-11a3-402d-dfed-efde848e7eee&dvIn[2][dvId]=fishing-map-vessel-track-v-3&timebarVisualisation=vessel

# https://globalfishingwatch.org/map/fishing-activity/default-public?latitude=11.518514803115004&longitude=-8.989016326741693&zoom=4.0891&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z&dvIn[0][id]=context-layer-eez&dvIn[0][cfg][vis]=true&dvIn[1][id]=fishing-ais-pipe-3&dvIn[1][cfg][vis]=false&dvIn[2][id]=vms&dvIn[2][cfg][vis]=false&dvIn[3][id]=vessel-1fe43f651-11a3-402d-dfed-efde848e7eee&dvIn[3][dvId]=fishing-map-vessel-track-v-3&timebarVisualisation=vessel


# https://globalfishingwatch.org/map/fishing-activity/default-public?latitude=11.518514803115004&longitude=-8.989016326741693&zoom=4.0891&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z&dvIn[0][id]=vessel-48b310f78-8edd-e2a3-8b30-722b2ee97cd6&dvIn[0][dvId]=fishing-map-vessel-track-v-3&dvIn[0][cfg][track]=public-global-all-tracks%3Av3.0&dvIn[0][cfg][info]=public-global-vessel-identity%3Av3.0&dvIn[0][cfg][events][0]=public-global-fishing-events%3Av3.0&dvIn[0][cfg][events][1]=public-global-port-visits-events%3Av3.0&dvIn[0][cfg][events][2]=public-global-encounters-events%3Av3.0&dvIn[0][cfg][events][3]=public-global-loitering-events%3Av3.0&dvIn[0][cfg][events][4]=public-global-gaps-events%3Av3.0&dvIn[0][cfg][relatedVesselIds][0]=1fe43f651-11a3-402d-dfed-efde848e7eee&dvIn[0][cfg][clr]=%23F95E5E&dvIn[1][id]=context-layer-eez&dvIn[1][cfg][vis]=true&dvIn[2][id]=fishing-ais-pipe-3&dvIn[2][cfg][vis]=false&dvIn[3][id]=vms&dvIn[3][cfg][vis]=false&timebarVisualisation=vessel&lTD=&fTD=

# https://globalfishingwatch.org/map/fishing-activity/default-public?latitude=11.518514803115004&longitude=-8.989016326741693&zoom=4.0891&start=2024-04-01T00%3A00%3A00.000Z&end=2024-07-01T00%3A00%3A00.000Z&dvIn[0][id]=vessel-48b310f78-8edd-e2a3-8b30-722b2ee97cd6&dvIn[0][dvId]=fishing-map-vessel-track-v-3&dvIn[0][cfg][track]=public-global-all-tracks%3Av3.0&dvIn[0][cfg][info]=public-global-vessel-identity%3Av3.0&dvIn[0][cfg][events][0]=public-global-fishing-events%3Av3.0&dvIn[0][cfg][events][1]=public-global-port-visits-events%3Av3.0&dvIn[0][cfg][events][2]=public-global-encounters-events%3Av3.0&dvIn[0][cfg][events][3]=public-global-loitering-events%3Av3.0&dvIn[0][cfg][events][4]=public-global-gaps-events%3Av3.0&dvIn[0][cfg][relatedVesselIds][0]=1fe43f651-11a3-402d-dfed-efde848e7eee&dvIn[0][cfg][clr]=%23F95E5E&dvIn[1][id]=context-layer-eez&dvIn[1][cfg][vis]=true&dvIn[2][id]=fishing-ais-pipe-3&dvIn[2][cfg][vis]=false&dvIn[3][id]=vms&dvIn[3][cfg][vis]=false&timebarVisualisation=vessel&lTD=&fTD=&visibleEvents[0]=fishing&visibleEvents[1]=port_visit
```

```{r manual rows for port calls}
colnames(tmt_review_new_v2)
colnames(full_dak_info)[1:26]

# just the final table columns 
interest_cols <- dplyr::select(tmt_review_new_v2,-1,-2, -3, -4, -5, -6, -7, -8, -9)

# manual data for two missing vessels 
haixin <- c('HAIXIN 29', 412549434, 'CHN', 'fishing', 'trawlers', 'COD', 'Pointe Noire', '06/02/2024 09:12', 
  '23/02/2024 11:29', '17.8', 'DAKAR', 'FALSE', '0', '','FALSE', '', 'FALSE', NA, 'FALSE', NA, 'TRUE', 
  '19', '48b310f78-8edd-e2a3-8b30-722b2ee97cd6', 'manual', 'manual', 'manual')
gueriden <- c('GUERIDIN', 227550000, 'FRA', 'fishing', 'tuna_purse_seines', 'CIV', 'Abidjan', '14/04/2024 08:03', 
  '27/04/2024 08:04', '17.8', 'DAKAR', 'TRUE', '487', 'CIV, GIN, GNB','FALSE', '', 'FALSE', NA, 'TRUE', 43, 'TRUE', 
  '52', '1fe43f651-11a3-402d-dfed-efde848e7eee', 'manual', 'manual', 'manual')

length(gueriden)

haixin_df <- data.frame(t(haixin))
gueriden_df <- data.frame(t(gueriden))
colnames(haixin_df) <- colnames(interest_cols)
colnames(gueriden_df) <- colnames(interest_cols)

# tack on extra rows 
full_q2_data <- rbind(interest_cols, haixin_df, gueriden_df)

write.csv(full_q2_data, here::here("data", "dakar_Q2_2024_07Aug2024.csv"), row.names=F)

```



## Figures 
```{r flag figure for Dakar}
full_q2_data$Flag <- full_q2_data$Flag2

full_q2_data %>%
  group_by(Flag) %>%
  summarize(vessels = n()) %>%
  plot_donut_chart(group_var = Flag,
                   value_var = vessels,
                   donut_title = 'Dakar voyages by\nflag',
                   add_labels = T,
                   show_legend = F,
                   label_frac = 0.025,
                   show_caption = T) 

ggsave( filename = here::here('outputs', 'figures', 'q2_24_proactive', paste0(country,"_", month,"_", "dakar_fishing_flags_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')

```

```{r type figure for Dakar}
library(ggrepel)

full_q2_data %>%
  group_by(vessel_class) %>%
  summarize(vessels = n()) %>%
  plot_donut_chart(group_var = vessel_class,
                   value_var = vessels,
                   donut_title = 'Dakar voyages by\nclass',
                   add_labels = T,
                   show_legend = F,
                   label_frac = 0.05,
                   show_caption = T) #+ 
  theme(text = element_text(size = 4),  
        axis.text=element_text(size=5), #change font size of axis text
        #axis.title=element_text(size=5), #change font size of axis titles
        plot.title=element_text(size=5), #change font size of plot title
        #legend.text=element_text(size=5), #change font size of legend text
        legend.title=element_text(size=5)) #%>%
  #geom_label_repel(data=full_q2_data, aes(y=vessles, label=vessel_class))

ggsave( filename = here::here('outputs', 'figures', 'q2_24_proactive', paste0(country,"_", month,"_", "vessel_class_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 7, 
       height = 7,
       bg = '#f7f7f7')

```


```{r gear figure for Dakar}
full_q2_data %>%
  group_by(vessel_type) %>%
  summarize(vessels = n()) %>%
  plot_donut_chart(group_var = vessel_type,
                   value_var = vessels,
                   donut_title = 'Dakar voyages by\ngear',
                   add_labels = T,
                   show_legend = F,
                   label_frac = 0.05,
                   show_caption = T) 

ggsave( filename = here::here('outputs', 'figures', 'q2_24_proactive', paste0(country,"_", month,"_", "fishing_gears_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')

```


```{r pull in the fishing data, echo=F, warning=F, include=FALSE}

q_confidence <- readr::read_file(here::here("queries","proactive", "proactive_fishing_locations.sql"))

fishing <- fishwatchr::gfw_query(query = glue::glue(q_confidence,
                                               voyages_table = "`world-fishing-827.scratch_max.voyages_dakar_q2_2024_pipe25`" 
                                               # min_date = "'2022-01-01'", 
                                               # max_date = "'2023-01-01'",
                                               ),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r voyage activity longline maps, echo=F, warning=F, include=FALSE}
# sense check the data 
fishing %>%
    group_by(ssvid) %>%
      summarise(positions = n(), 
                min_date = min(event_start), 
                max_date = max(event_end))

# add gear from TMT review 
gear <- distinct(dplyr::select(tmt_review_v2, MMSI, Flag, vessel_type)) %>% 
  mutate(ssvid=as.character(MMSI))

fishing_data <- left_join(fishing, gear, by = join_by(ssvid))

# bin the data
fishing_data$lat_bin <- round(fishing_data$lat_mean/0.5)*0.5
fishing_data$lon_bin <- round(fishing_data$lon_mean/0.5)*0.5

table(fishing_data$vessel_type)

# count positions in each lat lon bin
longline_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, vessel_type %in% c('drifting_longlines','set_longlines')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 500 
#set plot center 
new_center <- 40

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=40 +wktext"

# set plot limits bound on the data
bounding_atl <- transform_box(xlim = c(-60, 0),
                          ylim = c(30, -15),
                          output_crs = best_proj)

# map for atlantic longline 
atl_full <- longline_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      # limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atl$box_out[['xmin']], bounding_atl$box_out[['xmax']]),
      ylim = c(bounding_atl$box_out[['ymin']], bounding_atl$box_out[['ymax']]),
      crs = bounding_atl$out_crs) +
    # scale_x_continuous(breaks = custom_breaks, labels = custom_labels)+
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light') +
    theme(legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 6),
        legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 6),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(2, 'mm'),
      legend.key.width = unit(15,'mm'))


fishwatchr::add_little_globe(atl_full,
                             main_box = bounding_atl,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures','q2_24_proactive', paste0(country,"_", month,"_", "longline_map_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 15, 
       height = 17,
       bg = '#f7f7f7')

```


```{r voyage activity trawl maps, echo=F, warning=F, include=FALSE}
# add a different lat lon bin 
fishing_data$lat_bin <- round(fishing_data$lat_mean/0.1)*0.1
fishing_data$lon_bin <- round(fishing_data$lon_mean/0.1)*0.1


# count positions in each lat lon bin
trawl_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, vessel_type %in% c('trawlers')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 9000 
#set plot center 
new_center <- 17

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=17 +wktext"

# set plot limits bound on the data
bounding_wa <- transform_box(xlim = c(-20, -14),
                          ylim = c(16, 8.5),
                          output_crs = best_proj)

# trawl map 
trawl_full <- trawl_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                       limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_wa$box_out[['xmin']], bounding_wa$box_out[['xmax']]),
      ylim = c(bounding_wa$box_out[['ymin']], bounding_wa$box_out[['ymax']]),
      crs = bounding_wa$out_crs) +
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light')  +
    theme(legend.text = element_text(family = 'Roboto',
                                 color = '#848b9b',
                                 size = 6),
        legend.title = element_text(family = 'Roboto',
                                  face = 'bold',
                                  color = '#363c4c',
                                  size = 6),
      legend.position = 'bottom',
      legend.box = 'vertical',
      legend.key.height = unit(2, 'mm'),
      legend.key.width = unit(15,'mm'))


fishwatchr::add_little_globe(trawl_full,
                             main_box = bounding_wa,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures', 'q2_24_proactive', paste0(country,"_", month,"_", "trawl_map_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 15, 
       height = 17,
       bg = '#f7f7f7')

```


# Ghana 


```{r set date and port GHA parameters, echo=F, warning=F, include=FALSE}
start_date <- "'2024-01-01 00:00:00 UTC'" 
end_date <- "'2024-03-31 23:59:59 UTC'"
year <- 2024
country_iso3 <- "'GHA'"
port_name <- "'TEMA'"
q_confidence <- readr::read_file(file = here::here("queries", "op_fcwc_july_23", "q_fishing_vessels_confidence_fcwc_july_2023.sql"))

fv <- fishwatchr::gfw_query(query = glue::glue(q_confidence,
                                               aoi = "`world-fishing-827.scratch_max.fcwc_gha_civ_eez_20nm_buffer`", 
                                               min_date = "'2022-01-01'", 
                                               max_date = "'2023-01-01'", 
                                               year = 2022),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r voyages all, echo=F, warning=F, include=FALSE}
tem_voyages <- fishwatchr::gfw_query(query = glue::glue(voyages_q, 
                                                    start_date = start_date,
                                                    end_date = end_date,
                                                    year = year,
                                                    port_label = port_name,
                                                    port_iso = country_iso3),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r groom data to TMT format}
gha_voyages <- dplyr::select(tem_voyages, vessel_name=shipname, MMSI=ssvid,
   Flag=vessel_flag_best, vessel_class=vessel_class_best,
   vessel_type=geartype_best,  previous_port_country = start_port_iso3,
   previous_port = start_port_label, trip_start, trip_start_confidence, trip_end, trip_end_confidence, trip_duration_days,
   end_port = end_port_label, fishing=num_fishing, fishing_hours, fishing_eez=eezs, fishing_hs =high_seas, fishing_rfmos = rfmos, encounter= 1, num_encounters=num_encounters, loitering=1, num_loitering, vessel_id=vessel_id, trip_id=trip_id)
   #gaps=1, num_gaps, total_gap_hours)

# overwrite encounters T/F
gha_voyages$encounter <- ifelse(is.na(gha_voyages$num_encounters), FALSE, TRUE)

# overwrite fishing T/F
gha_voyages$loitering <- ifelse(is.na(gha_voyages$num_loitering), FALSE, TRUE)

# overwrite loitering T/F
gha_voyages$fishing <- ifelse(is.na(gha_voyages$fishing), FALSE, TRUE)

# overwrite high_sea T/F
gha_voyages$fishing_hs <- ifelse(is.na(gha_voyages$fishing_hs), FALSE, TRUE)

```


```{r voyages extra ais queries gha can't link up, echo=F, warning=F, include=FALSE}

extra_gha <- fishwatchr::gfw_query(query = c("SELECT * FROM `world-fishing-827.scratch_max.aiscoverage_tema_2024-q1_pipe25`"),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r final r manipulation}

full_tem_info <- left_join(gha_voyages, dplyr::select(extra_gha,vessel_id, trip_id, at_dock, percent_ais_voyage), by=c('vessel_id','trip_id'))

write.csv(dplyr::select(full_tem_info,-vessel_id, -trip_id), here::here("data", "tema_Q1_2024_19Apr2024.csv"), row.names=F)
```





























```{r carrier visits all, echo=F, warning=F, include=FALSE}

carrier_voyages_q <- readr::read_file(here::here("queries", "proactive", "recent_carrier_voyages_c2.sql"))

carrier_voyages <- fishwatchr::gfw_query(query = glue::glue(carrier_voyages_q),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r fishing voyages all, echo=F, warning=F, include=FALSE}

fishing_voyages_q <- readr::read_file(here::here("queries","proactive", "recent_fishing_voyages_c2_v2.sql"))

fishing_voyages <- fishwatchr::gfw_query(query = glue::glue(fishing_voyages_q),
                                 run_query = TRUE,
                                 con = con)$data
```

```{r estabish and write out voyages data for cv & fv, echo=F, warning=F, include=FALSE}
voyages <- bind_rows(carrier_voyages, fishing_voyages)

voyages %>% 
  write_csv(here::here("data", "proactive", 
         paste0(country,"_", month ,"_voyages",str_replace_all(Sys.Date(), '-','_'),".csv")))
```

```{r basic flag statistics on voyages, echo=F, warning=F, include=FALSE}

fishing_voyages %>%
  group_by(flag) %>%
  summarize(vessels = n()) %>%
  plot_donut_chart(group_var = flag,
                   value_var = vessels,
                   donut_title = 'Fishing vessels by\nflag',
                   add_labels = T,
                   show_legend = F,
                   label_frac = 0.1,
                   show_caption = T) 

ggsave( filename = here::here('outputs', 'figures', paste0(country,"_", month,"_", "fishing_flags_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')
```

```{r basic gear statistics on voyages, echo=F, warning=F, include=FALSE}

fishing_voyages %>%
  group_by(gear) %>%
  summarize(vessels = n()) %>%
  plot_donut_chart(group_var = gear,
                   value_var = vessels,
                   donut_title = 'Fishing vessels by\ngear',
                   add_labels = T,
                   show_legend = F,
                   label_frac = 0.1,
                   show_caption = T) 

ggsave( filename = here::here('outputs', 'figures', paste0(country,"_", month,"_", "fishing_gears_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 10, 
       height = 10,
       bg = '#f7f7f7')
```


```{r voyage activity, echo=F, warning=F, include=FALSE}

fishing_voyages_activity_q <- readr::read_file(here::here("queries","proactive", "fishing_voyage_activity.sql"))

fishing_data <- fishwatchr::gfw_query(query = glue::glue(fishing_voyages_activity_q),
                                 run_query = TRUE,
                                 con = con)$data

```

```{r voyage activity longline maps, echo=F, warning=F, include=FALSE}
# sense check the data 
fishing_data %>%
    group_by(ssvid) %>%
      summarise(positions = n(), 
                min_date = min(timestamp), 
                max_date = max(timestamp))

# add fishing hours variable 
fishing_data$fishing_hours <- ifelse(fishing_data$nnet_score   > 0.5 , fishing_data$hours, 0) 
fishing_data$fishing_hours[is.na(fishing_data$fishing_hours)] <- 0

# bin the data
fishing_data$lat_bin <- round(fishing_data$lat/0.5)*0.5
fishing_data$lon_bin <- round(fishing_data$lon/0.5)*0.5

# count positions in each lat lon bin
longline_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, gear %in% c('drifting_longlines','set_longlines')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        hours = sum(hours),
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 500 
#set plot center 
new_center <- 40

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=40 +wktext"

# set plot limits bound on the data
bounding_atl <- transform_box(xlim = c(-60, 0),
                          ylim = c(30, -15),
                          output_crs = best_proj)

# # # Specify custom x-axis breaks and labels
# custom_breaks <- c(150, 170, -170)
# custom_labels <- c("150° E", "170° E","170° W")

atl_full <- longline_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      # limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_atl$box_out[['xmin']], bounding_atl$box_out[['xmax']]),
      ylim = c(bounding_atl$box_out[['ymin']], bounding_atl$box_out[['ymax']]),
      crs = bounding_atl$out_crs) +
    # scale_x_continuous(breaks = custom_breaks, labels = custom_labels)+
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(atl_full,
                             main_box = bounding_atl,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures', paste0(country,"_", month,"_", "longline_map_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 20, 
       height = 20,
       bg = '#f7f7f7')

```


```{r voyage activity trawl maps, echo=F, warning=F, include=FALSE}
# count positions in each lat lon bin
trawl_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, gear %in% c('trawlers', 'fishing')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        hours = sum(hours),
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

# set upper limit
up_lim <- 500 
#set plot center 
new_center <- 17

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=17 +wktext"

# set plot limits bound on the data
bounding_wa <- transform_box(xlim = c(-20, -13),
                          ylim = c(20, 7.5),
                          output_crs = best_proj)

# # # Specify custom x-axis breaks and labels
# custom_breaks <- c(150, 170, -170)
# custom_labels <- c("150° E", "170° E","170° W")

trawl_full <- trawl_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      # limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_wa$box_out[['xmin']], bounding_wa$box_out[['xmax']]),
      ylim = c(bounding_wa$box_out[['ymin']], bounding_wa$box_out[['ymax']]),
      crs = bounding_wa$out_crs) +
    # scale_x_continuous(breaks = custom_breaks, labels = custom_labels)+
    labs(fill = 'Fishing Hours') +
    theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(trawl_full,
                             main_box = bounding_wa,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures', paste0(country,"_", month,"_", "trawl_map_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 20, 
       height = 20,
       bg = '#f7f7f7')

```

```{r voyage activity purse seine maps, echo=F, warning=F, include=FALSE}
# count positions in each lat lon bin
ps_raster <- 
  # filter out low speeds while vessel in port 
  filter(fishing_data, gear %in% c('tuna_purse_seines')) %>%
    group_by(lat_bin, lon_bin) %>%
      summarise(
        hours = sum(hours),
        fishing_hours = sum(fishing_hours),
        vessels = n_distinct(ssvid)
      )

#set plot center 
new_center <- 40

# set proj for bounding box
best_proj <- "+proj=eqearth +lon_0=40 +wktext"

# set plot limits bound on the data
bounding_ps <- transform_box(xlim = c(-40, -13),
                          ylim = c(25, 7.5),
                          output_crs = best_proj)

ps_full <- ps_raster %>%
  recenter_raster(raster_df = .,
                  res = 1,
                  x_lab = 'lon_bin',
                  y_lab = 'lat_bin',
                  fill_lab = 'fishing_hours',
                  center = new_center) %>% 
  ggplot()+
  geom_gfw_outline(center = new_center, theme = "dark") +
  geom_raster(aes(x= lon_bin, y=lat_bin, fill = fishing_hours)) +
    geom_gfw_eez(theme = 'dark', alpha = 0.9, center = new_center) +
    geom_gfw_land(theme = 'dark', center = new_center) +
    # geom_sf(pipa, fill=NA, colour='green')+
    scale_fill_gradientn(colors = gfw_palette('map_effort_dark'),
                      # limits = c(0,up_lim),
                       oob = scales::squish,
                       na.value = NA) +   
    coord_sf(xlim = c(bounding_ps$box_out[['xmin']], bounding_ps$box_out[['xmax']]),
      ylim = c(bounding_ps$box_out[['ymin']], bounding_ps$box_out[['ymax']]),
      crs = bounding_ps$out_crs) +
    labs(fill = 'Fishing Hours')  +
    theme_gfw_map(theme = 'light') 


fishwatchr::add_little_globe(ps_full,
                             main_box = bounding_ps,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright')

ggsave(filename = here::here('outputs', 'figures', paste0(country,"_", month,"_", "ps_map_",str_replace_all(Sys.Date(), '-','_'),".png")), 
       units = 'cm', 
       width = 20, 
       height = 20,
       bg = '#f7f7f7')

```
